// packages/mochart-demo-vue/src/components/misc/DocsLinks.vue
<script setup lang="ts">
import { computed } from 'vue';

import { demoText, getReferenceSectionIds, getReferenceSectionUrl } from '@mochart/demo-common';

// Links into the documentation site's config reference for the sections the
// edited config actually uses (see demo-common docsLinks).
interface Props {
  config: Record<string, unknown> | null | undefined;
}

const props = defineProps<Props>();

const sectionIds = computed(() => getReferenceSectionIds(props.config));
</script>

<template>
  <div v-if="sectionIds.length > 0" class="mochart-demo-docs-links">
    <span>{{ demoText.docsLinks.label }}&nbsp;</span>
    <template v-for="(sectionId, index) in sectionIds" :key="sectionId">
      <span v-if="index > 0"> · </span>
      <a :href="getReferenceSectionUrl(sectionId)" :title="demoText.docsLinks.tooltipPrefix + sectionId">{{ sectionId }}</a>
    </template>
  </div>
</template>

// packages/mochart-demo-angular/src/components/misc/docs-links.ts
import { Component, Input, computed, signal } from '@angular/core';

import { demoText, getReferenceSectionIds, getReferenceSectionUrl } from '@mochart/demo-common';

/**
 * Links into the documentation site's config reference for the sections the
 * edited config actually uses (see demo-common docsLinks).
 */
@Component({
  selector: 'app-docs-links',
  styles: [':host { display: contents; }'],
  template: `
    @if (sectionIds().length > 0) {
      <div class="mochart-demo-docs-links">
        <span>{{ text.label }}&nbsp;</span>
        @for (sectionId of sectionIds(); track sectionId; let index = $index) {
          @if (index > 0) {
            <span> · </span>
          }
          <a [href]="sectionUrl(sectionId)" [title]="text.tooltipPrefix + sectionId">{{ sectionId }}</a>
        }
      </div>
    }
  `
})
export class DocsLinks {
  readonly text = demoText.docsLinks;

  private readonly configSignal = signal<Record<string, unknown> | null | undefined>(null);

  @Input({ required: true }) set config(value: Record<string, unknown> | null | undefined) {
    this.configSignal.set(value);
  }

  readonly sectionIds = computed(() => getReferenceSectionIds(this.configSignal()));

  sectionUrl(sectionId: string): string {
    return getReferenceSectionUrl(sectionId);
  }
}
