// packages/mochart-demo-react/src/components/misc/ExportButtons.tsx
import React from 'react';
import Icon from './Icon';

import { exportPNG, exportSVG } from '@mochart/export';

import { demoText } from '@mochart/demo-common';

import ButtonWithTooltip from './ButtonWithTooltip';

// Download buttons for the chart found inside the container element
// (mochart-export locates the chart svg itself).
interface Props {
  idPrefix: string;
  getContainer: () => Element | null;
  disabled?: boolean;
}

export default function ExportButtons({ idPrefix, getContainer, disabled = false }: Props) {
  const onExportPng = () => {
    const container = getContainer();
    if (container) {
      void exportPNG(container);
    }
  };

  const onExportSvg = () => {
    const container = getContainer();
    if (container) {
      exportSVG(container);
    }
  };

  return (
    <div className="btn-group">
      <ButtonWithTooltip id={idPrefix + "-export-png"} disabled={disabled} label={demoText.exportButtons.png.label}
        tooltipText={demoText.exportButtons.png.tooltip} tooltipPlacement="top-start"
        onClick={onExportPng} aria-label={demoText.exportButtons.png.aria}>
        <Icon size="lg" fixedWidth={true} name="file-image" />
      </ButtonWithTooltip>
      <ButtonWithTooltip id={idPrefix + "-export-svg"} disabled={disabled} label={demoText.exportButtons.svg.label}
        tooltipText={demoText.exportButtons.svg.tooltip} tooltipPlacement="top-start"
        onClick={onExportSvg} aria-label={demoText.exportButtons.svg.aria}>
        <Icon size="lg" fixedWidth={true} name="file-code" />
      </ButtonWithTooltip>
    </div>
  );
}

// packages/mochart-demo-angular/src/components/misc/export-buttons.ts
import { Component, Input } from '@angular/core';

import { exportPNG, exportSVG } from '@mochart/export';

import { demoText } from '@mochart/demo-common';

import { ButtonWithTooltip } from './button-with-tooltip';
import { Icon } from './icon';

/**
 * Download buttons for the chart found inside the container element
 * (mochart-export locates the chart svg itself).
 */
@Component({
  selector: 'app-export-buttons',
  imports: [ButtonWithTooltip, Icon],
  styles: [':host { display: contents; }'],
  template: `
    <div class="btn-group">
      <app-button-with-tooltip [id]="idPrefix + '-export-png'" [disabled]="disabled" [label]="text.png.label"
                               [tooltipText]="text.png.tooltip" tooltipPlacement="top-start"
                               [onClick]="onExportPng" [aria-label]="text.png.aria">
        <app-icon size="lg" [fixedWidth]="true" name="file-image" />
      </app-button-with-tooltip>
      <app-button-with-tooltip [id]="idPrefix + '-export-svg'" [disabled]="disabled" [label]="text.svg.label"
                               [tooltipText]="text.svg.tooltip" tooltipPlacement="top-start"
                               [onClick]="onExportSvg" [aria-label]="text.svg.aria">
        <app-icon size="lg" [fixedWidth]="true" name="file-code" />
      </app-button-with-tooltip>
    </div>
  `
})
export class ExportButtons {
  readonly text = demoText.exportButtons;

  @Input({ required: true }) idPrefix!: string;
  @Input({ required: true }) getContainer!: () => Element | null;
  @Input() disabled = false;

  onExportPng = (): void => {
    const container = this.getContainer();
    if (container) {
      void exportPNG(container);
    }
  };

  onExportSvg = (): void => {
    const container = this.getContainer();
    if (container) {
      exportSVG(container);
    }
  };
}
