// packages/mochart-demo-angular/src/components/misc/button-with-tooltip.ts
import { Component, Input } from '@angular/core';

/**
 * The react demo used reactstrap's Tooltip; the native title attribute
 * covers the same hint here without a popper-style positioning library.
 * tooltipPlacement is accepted for call-site parity but unused. `label`
 * renders visible text beside the icon; `pressed` marks the button as a
 * toggle (aria-pressed + active styling). The aria-label lands on the
 * button element via the `aria-label` input alias.
 */
@Component({
  selector: 'app-button-with-tooltip',
  styles: [':host { display: contents; }'],
  template: `
    <span class="button-with-tooltip">
      <button [id]="id" type="button" [class]="'btn btn-' + color + (pressed ? ' active' : '')"
              [disabled]="disabled" [attr.title]="tooltipText ?? null"
              [attr.aria-pressed]="pressed === undefined ? null : pressed"
              [attr.aria-label]="ariaLabel ?? null" (click)="onClick()">
        <ng-content />@if (label) {<span class="btn-label">{{ label }}</span>}
      </button>
    </span>
  `
})
export class ButtonWithTooltip {
  @Input({ required: true }) id!: string;
  @Input() tooltipText?: string;
  @Input() tooltipPlacement?: string;
  @Input() disabled = false;
  @Input({ required: true }) onClick!: () => void;
  @Input() color = 'secondary';
  @Input() label?: string;
  @Input() pressed?: boolean;
  @Input('aria-label') ariaLabel?: string;
}

// packages/mochart-demo-svelte/src/components/misc/ButtonWithTooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  // The react demo used reactstrap's Tooltip; the native title attribute
  // covers the same hint here without a popper-style positioning library.
  // tooltipPlacement is accepted for call-site parity but unused.
  // `label` renders visible text beside the icon; `pressed` marks the button
  // as a toggle (aria-pressed + active styling).
  interface Props {
    id: string;
    tooltipText?: string;
    tooltipPlacement?: string;
    disabled?: boolean;
    onClick: () => void;
    color?: string;
    label?: string;
    pressed?: boolean;
    children: Snippet;
    [key: string]: unknown;
  }

  let {
    id,
    tooltipText,
    tooltipPlacement = void 0,
    disabled = false,
    onClick,
    color = 'secondary',
    label = void 0,
    pressed = void 0,
    children,
    ...rest
  }: Props = $props();
</script>

<span class="button-with-tooltip">
  <button {id} type="button" class={`btn btn-${color}` + (pressed ? ' active' : '')} {disabled} title={tooltipText}
          aria-pressed={pressed === void 0 ? void 0 : pressed} onclick={onClick} {...rest}>
    {@render children()}{#if label}<span class="btn-label">{label}</span>{/if}
  </button>
</span>
