// packages/mochart-demo-react/src/components/misc/DocsLinks.tsx
import React from 'react';

import { demoText, getReferenceSectionIds, getReferenceSectionUrl } from '@mochart/demo-common';

// Links into the documentation site's config reference for the sections the
// edited config actually uses (see demo-common docsLinks).
interface Props {
  config: Record<string, unknown> | null | undefined;
}

export default function DocsLinks({ config }: Props) {
  const sectionIds = getReferenceSectionIds(config);
  if (sectionIds.length === 0) {
    return null;
  }
  return (
    <div className="mochart-demo-docs-links">
      <span>{demoText.docsLinks.label} </span>
      {sectionIds.map((sectionId, index) => (
        <React.Fragment key={sectionId}>
          {index > 0 ? ' · ' : null}
          <a href={getReferenceSectionUrl(sectionId)} title={demoText.docsLinks.tooltipPrefix + sectionId}>{sectionId}</a>
        </React.Fragment>
      ))}
    </div>
  );
}

// packages/mochart-demo-svelte/src/components/misc/DocsLinks.svelte
<script lang="ts">
  import { demoText, getReferenceSectionIds, getReferenceSectionUrl } from '@mochart/demo-common';

  // Links into the documentation site's config reference for the sections the
  // edited config actually uses (see demo-common docsLinks).
  interface Props {
    config: Record<string, unknown> | null | undefined;
  }

  let { config }: Props = $props();

  const sectionIds = $derived(getReferenceSectionIds(config));
</script>

{#if sectionIds.length > 0}
  <div class="mochart-demo-docs-links">
    <span>{demoText.docsLinks.label} </span>
    {#each sectionIds as sectionId, index (sectionId)}
      {#if index > 0}{' · '}{/if}
      <a href={getReferenceSectionUrl(sectionId)} title={demoText.docsLinks.tooltipPrefix + sectionId}>{sectionId}</a>
    {/each}
  </div>
{/if}
