// packages/mochart-demo-svelte/src/components/multi/DemoMulti.svelte
<script lang="ts">
  import DemosTab from '../demos/DemosTab.svelte';
  import ChartsTab from './ChartsTab.svelte';
  import ErrorTab from '../misc/ErrorTab.svelte';

  import type { DemoData, DemoMode, OnDemoModeChanged, OnDemoChanged } from '../../types';

  interface Props {
    demoData: DemoData;
    demoMode: DemoMode;
    initialDemoId: string;
    onDemoModeChanged: OnDemoModeChanged;
    onDemoChanged: OnDemoChanged;
  }

  const eventKeyChart = 1;
  const eventKeyDemo = 2;

  function getActiveKeyForInitialDemoId(initialDemoId: string): number {
    return initialDemoId === 'demos' ? eventKeyDemo : eventKeyChart;
  }

  let { demoData, demoMode, initialDemoId, onDemoModeChanged, onDemoChanged }: Props = $props();

  let demoId = $state(initialDemoId);
  let activeKey = $state(getActiveKeyForInitialDemoId(initialDemoId));

  let previousInitialDemoId = initialDemoId;
  $effect.pre(() => {
    if (initialDemoId !== previousInitialDemoId) {
      previousInitialDemoId = initialDemoId;
      activeKey = getActiveKeyForInitialDemoId(initialDemoId);
      demoId = initialDemoId;
    }
  });

  function onDemoChange(nextDemoId: string) {
    demoId = nextDemoId;
    onDemoChanged(nextDemoId);
  }

  function handleSelect(nextActiveKey: number) {
    activeKey = nextActiveKey;
  }

  const isDemos = $derived(initialDemoId === 'demos');
</script>

<div class="mochart-demo-container multi">
  <div class="mochart-demo-tabs-container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <button type="button" class={"nav-link" + (activeKey === eventKeyDemo ? " active" : "")}
                onclick={() => handleSelect(eventKeyDemo)}>
          Demos
        </button>
      </li>
      <li class="nav-item" style={isDemos ? "display: none;" : void 0}>
        <button type="button" class={"nav-link" + (activeKey === eventKeyChart ? " active" : "")}
                onclick={() => handleSelect(eventKeyChart)}>
          Chart
        </button>
      </li>
    </ul>
  </div>
  <div class="mochart-demo-content-pane">
    {#if isDemos}
      <div class="mochart-demo-content single-tab">
        <DemosTab active={activeKey === eventKeyDemo} {demoData} {demoMode} {demoId}
                  {onDemoModeChanged} {onDemoChange} />
      </div>
    {:else}
      <div class="mochart-demo-content">
        <ErrorTab active={activeKey === eventKeyDemo}>
          <DemosTab active={activeKey === eventKeyDemo} {demoData} {demoMode} {demoId}
                    {onDemoModeChanged} {onDemoChange} />
        </ErrorTab>
        <ErrorTab active={activeKey === eventKeyChart}>
          <ChartsTab active={activeKey === eventKeyChart} demoObject={demoData.demoObjectMap[demoId]} />
        </ErrorTab>
      </div>
    {/if}
  </div>
</div>

// packages/mochart-demo-lit/src/components/multi/demo-multi.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { PropertyValues } from 'lit';

import { LightElement } from '../misc/LightElement';

import '../demos/demos-tab';
import './charts-tab';
import '../misc/error-tab';

import type { DemoData, DemoMode, OnDemoModeChanged, OnDemoChanged } from '../../types';

const eventKeyChart = 1;
const eventKeyDemo = 2;

function getActiveKeyForInitialDemoId(initialDemoId: string): number {
  return initialDemoId === 'demos' ? eventKeyDemo : eventKeyChart;
}

@customElement('demo-multi')
export class DemoMulti extends LightElement {
  @property({ attribute: false }) demoData!: DemoData;
  @property({ attribute: false }) demoMode!: DemoMode;
  @property({ attribute: false }) initialDemoId!: string;
  @property({ attribute: false }) onDemoModeChanged!: OnDemoModeChanged;
  @property({ attribute: false }) onDemoChanged!: OnDemoChanged;

  @state() private demoId = '';
  @state() private activeKey = eventKeyChart;

  override willUpdate(changed: PropertyValues<this>): void {
    if (changed.has('initialDemoId')) {
      this.activeKey = getActiveKeyForInitialDemoId(this.initialDemoId);
      this.demoId = this.initialDemoId;
    }
  }

  private onDemoChange = (nextDemoId: string): void => {
    this.demoId = nextDemoId;
    this.onDemoChanged(nextDemoId);
  };

  private handleSelect(nextActiveKey: number): void {
    this.activeKey = nextActiveKey;
  }

  override render(): unknown {
    const isDemos = this.initialDemoId === 'demos';
    const demosTab = html`<demos-tab .active=${this.activeKey === eventKeyDemo} .demoData=${this.demoData} .demoMode=${this.demoMode} .demoId=${this.demoId}
        .onDemoModeChanged=${this.onDemoModeChanged} .onDemoChange=${this.onDemoChange}></demos-tab>`;
    return html`<div class="mochart-demo-container multi">
      <div class="mochart-demo-tabs-container">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <button type="button" class=${'nav-link' + (this.activeKey === eventKeyDemo ? ' active' : '')}
                    @click=${() => this.handleSelect(eventKeyDemo)}>
              Demos
            </button>
          </li>
          <li class="nav-item" style=${isDemos ? 'display: none;' : ''}>
            <button type="button" class=${'nav-link' + (this.activeKey === eventKeyChart ? ' active' : '')}
                    @click=${() => this.handleSelect(eventKeyChart)}>
              Chart
            </button>
          </li>
        </ul>
      </div>
      <div class="mochart-demo-content-pane">
        ${isDemos
          ? html`<div class="mochart-demo-content single-tab">${demosTab}</div>`
          : html`<div class="mochart-demo-content">
              <error-tab .active=${this.activeKey === eventKeyDemo} .content=${() => demosTab}></error-tab>
              <error-tab .active=${this.activeKey === eventKeyChart} .content=${() =>
                html`<charts-tab .active=${this.activeKey === eventKeyChart} .demoObject=${this.demoData.demoObjectMap[this.demoId]}></charts-tab>`}></error-tab>
            </div>`}
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-multi': DemoMulti;
  }
}
