// packages/mochart-demo-vue/src/components/sparkline/DemoSparkline.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { DefaultChart } from '@mochart/vue';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';

import BackToDemosButton from '../misc/BackToDemosButton.vue';
import ButtonWithTooltip from '../misc/ButtonWithTooltip.vue';
import Icon from '../misc/Icon.vue';
import SiteRootButton from '../misc/SiteRootButton.vue';
import ThemeToggleButton from '../misc/ThemeToggleButton.vue';

interface Props {
  siteRootUrl?: string;
  onBackToDemos: () => void;
}

const props = defineProps<Props>();

const text = demoText.sparklinePage;

// The Randomize button steps every metric's dataset in lockstep; each chart's
// data (and each table row's latest text) is derived from the current step.
const step = ref(0);

const inlineData = computed(() => inlineSparklineMetrics.map(metric => metric.generate(step.value)));
const tableData = computed(() => tableSparklineMetrics.map(metric => metric.generate(step.value)));

function onRandomize() {
  step.value++;
}
</script>

<template>
  <div class="mochart-demo-container">
    <div class="mochart-demo-tabs-container">
      <div class="mochart-demo-nav-group">
        <SiteRootButton :site-root-url="props.siteRootUrl" />
        <BackToDemosButton :on-back-to-demos="props.onBackToDemos" />
      </div>
      <ThemeToggleButton />
    </div>
    <div class="sparkline-page">
      <!-- The intro paragraph: copy segments with the inline metrics between
           them. Keep {{ segment }} and the span adjacent so the segments'
           built-in spacing survives template whitespace condensing. -->
      <p class="sparkline-intro">
        <template v-for="(segment, i) in text.intro" :key="i">{{ segment }}<span v-if="inlineSparklineMetrics[i] !== undefined" class="sparkline-inline">
          <DefaultChart :config="inlineSparklineMetrics[i].config" :data="inlineData[i]"
                        :width="inlineSparklineMetrics[i].width" :height="inlineSparklineMetrics[i].height" />
        </span></template>
      </p>
      <div class="sparkline-controls">
        <ButtonWithTooltip id="sparkline-randomize" color="primary" :label="text.randomize.label"
                           :tooltip-text="text.randomize.tooltip" :on-click="onRandomize"
                           :aria-label="text.randomize.aria">
          <Icon :fixed-width="true" name="dice" />
        </ButtonWithTooltip>
      </div>
      <table class="sparkline-table">
        <thead>
          <tr>
            <th>{{ text.table.metric }}</th>
            <th>{{ text.table.latest }}</th>
            <th>{{ text.table.trend }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(metric, i) in tableSparklineMetrics" :key="metric.id">
            <td>{{ metric.label }}</td>
            <td class="sparkline-value">{{ metric.latestText(tableData[i]) }}</td>
            <td class="sparkline-cell">
              <DefaultChart :config="metric.config" :data="tableData[i]"
                            :width="metric.width" :height="metric.height" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// packages/mochart-demo-react/src/components/sparkline/DemoSparkline.tsx
import { Fragment, useState } from 'react';

import { DefaultChart } from '@mochart/react';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';
import type { SparklineMetric } from '@mochart/demo-common';

import Icon from '../misc/Icon';
import ButtonWithTooltip from '../misc/ButtonWithTooltip';
import { SiteRootButton, BackToDemosButton, ThemeToggleButton } from '../misc/ModeSwitcher';

import type { OnBackToDemos } from '../../types';

interface DemoSparklineProps {
  siteRootUrl?: string;
  onBackToDemos: OnBackToDemos;
}

// Every sparkline mounts at the metric's explicit pixel size (no auto-sizing):
// inline metrics are word-sized, table cells larger.
function SparklineChart({ metric, step }: { metric: SparklineMetric; step: number }) {
  return <DefaultChart config={metric.config} data={metric.generate(step)} width={metric.width} height={metric.height} />;
}

function SparklineRow({ metric, step }: { metric: SparklineMetric; step: number }) {
  const data = metric.generate(step);
  return (
    <tr>
      <td>{metric.label}</td>
      <td className="sparkline-value">{metric.latestText(data)}</td>
      <td className="sparkline-cell">
        <DefaultChart config={metric.config} data={data} width={metric.width} height={metric.height} />
      </td>
    </tr>
  );
}

export default function DemoSparkline({ siteRootUrl, onBackToDemos }: DemoSparklineProps) {
  const text = demoText.sparklinePage;
  const [step, setStep] = useState(0);

  const onRandomize = () => setStep(prevStep => prevStep + 1);

  return (
    <div className="mochart-demo-container">
      <div className="mochart-demo-tabs-container">
        <div className="mochart-demo-nav-group">
          <SiteRootButton siteRootUrl={siteRootUrl} />
          <BackToDemosButton onBackToDemos={onBackToDemos} />
        </div>
        <ThemeToggleButton />
      </div>
      <div className="sparkline-page">
        {/* The intro paragraph: copy segments with the inline metrics between them. */}
        <p className="sparkline-intro">
          {text.intro.map((segment, i) => {
            const metric = inlineSparklineMetrics[i];
            return (
              <Fragment key={i}>
                {segment}
                {metric !== undefined ? (
                  <span className="sparkline-inline"><SparklineChart metric={metric} step={step} /></span>
                ) : null}
              </Fragment>
            );
          })}
        </p>
        <div className="sparkline-controls">
          <ButtonWithTooltip id="sparkline-randomize" label={text.randomize.label} color="primary"
            tooltipText={text.randomize.tooltip} onClick={onRandomize} aria-label={text.randomize.aria}>
            <Icon fixedWidth={true} name="dice" />
          </ButtonWithTooltip>
        </div>
        <table className="sparkline-table">
          <thead>
            <tr>
              <th>{text.table.metric}</th>
              <th>{text.table.latest}</th>
              <th>{text.table.trend}</th>
            </tr>
          </thead>
          <tbody>
            {tableSparklineMetrics.map(metric => <SparklineRow key={metric.id} metric={metric} step={step} />)}
          </tbody>
        </table>
      </div>
    </div>
  );
}
