// packages/mochart-demo-lit/src/components/multi/charts-tab.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { ref } from 'lit/directives/ref.js';
import type { PropertyValues } from 'lit';

import { chart } from '@mochart/lit';
import { exportChartsPNG, exportChartsSVG } from '@mochart/export';

import { getChartExportOptions, buildMochartDemoConfig, consumeShareState, getDataProvidersForDataCount, getPieSlices, getPieStepCycle, getPieStepSuppressedIds } from '@mochart/demo-common';
import type { ShareState } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';
import { ElementSizeController } from '../misc/ElementSizeController';
import './charts-controls';

import type { Demo, DataRow, FilteredSeriesIds, ChartDataProviderLike, MochartDemoConfig } from '../../types';

const scrollWidthOffset = 20;

const defaultChartRows = 2;
const defaultChartCols = 2;

function clampGrid(value: number): number {
  return Math.min(4, Math.max(1, Math.round(value)));
}

@customElement('charts-tab')
export class ChartsTab extends LightElement {
  @property({ attribute: false }) demoObject!: Demo;
  @property({ attribute: false }) active = false;

  private intervalId: ReturnType<typeof setInterval> | null = null;

  @state() private playing = false;
  @state() private chartRows = defaultChartRows;
  @state() private chartCols = defaultChartCols;
  private rate = 2000;
  @state() private mochartDemoConfig!: MochartDemoConfig;
  @state() private data: DataRow[] = [];
  private dataCount = 0;
  private currentDataCount = 0;
  // Pie mode steps a suppression pattern instead of data prefixes: chart i at
  // step s suppresses the last (s + i) mod cycle slices, so the grid shows
  // different-sized views of the same pie and stepping animates all charts.
  private sliceIds: string[] = [];
  @state() private dataProviders: ChartDataProviderLike[] = [];
  @state() private focusedGroupIndices: number[] = [];
  private focusedGroupIndex = -1;
  @state() private focusedSeriesAxisId: string | null = null;
  @state() private focusedSeriesId: string | null = null;
  @state() private filteredSeriesIds: FilteredSeriesIds = {};

  // Measured size of the charts grid.
  private size = new ElementSizeController(this);

  private initFocusAndFiltered(): void {
    this.focusedGroupIndex = -1;
    this.focusedSeriesAxisId = null;
    this.focusedSeriesId = null;
    this.filteredSeriesIds = {};
  }

  private stepCycle(): number {
    return this.mochartDemoConfig.pieMode ? getPieStepCycle(this.sliceIds) : this.dataCount;
  }

  private resetStep(): number {
    return this.mochartDemoConfig.pieMode ? 0 : this.dataCount;
  }

  // A shared `step` seeks the playback position; otherwise start on the full
  // set (pie mode starts at step 0 — the grid's staggered initial view).
  private initForDemoObject(step?: number): void {
    this.mochartDemoConfig = buildMochartDemoConfig(this.demoObject.config);
    this.initFocusAndFiltered();
    this.playing = false;
    this.data = this.demoObject.data;
    this.dataCount = this.data.length;
    this.sliceIds = this.mochartDemoConfig.pieMode ? getPieSlices(this.mochartDemoConfig.mochartConfig).map(slice => slice.id) : [];
    const cycle = this.stepCycle();
    this.currentDataCount = step !== undefined && cycle > 0
      ? ((Math.round(step) % cycle) + cycle) % cycle
      : this.resetStep();
    this.dataProviders = getDataProvidersForDataCount(this.mochartDemoConfig.mochartConfig, this.data, this.chartRows * this.chartCols, this.currentDataCount);
    this.focusedGroupIndices = this.dataProviders.map(() => -1);
  }

  override willUpdate(changed: PropertyValues<this>): void {
    if (!this.hasUpdated) {
      // A share link restores the grid size, playback step and interval.
      const shared = consumeShareState('multi');
      const sharedMulti = shared && shared.mode === 'multi' ? shared : null;
      let step: number | undefined;
      if (sharedMulti) {
        this.chartRows = clampGrid(sharedMulti.rows);
        this.chartCols = clampGrid(sharedMulti.cols);
        this.rate = sharedMulti.interval;
        step = sharedMulti.step;
      }
      this.initForDemoObject(step);
      return;
    }
    if (changed.has('demoObject')) {
      this.initForDemoObject();
    }
    if (changed.has('active')) {
      this.onStopClick();
    }
  }

  // The whole grid exports as one tiled image; share captures the grid size,
  // playback step and interval so the link restores the same view.
  private getChartContainers(): Element[] {
    return Array.from(this.querySelectorAll('.multi-mochart-chart'));
  }

  private onExportPng = (): void => {
    const containers = this.getChartContainers();
    if (containers.length > 0) {
      void exportChartsPNG(containers, { cols: this.chartCols, ...getChartExportOptions() });
    }
  };

  private onExportSvg = (): void => {
    const containers = this.getChartContainers();
    if (containers.length > 0) {
      exportChartsSVG(containers, { cols: this.chartCols, ...getChartExportOptions() });
    }
  };

  private getShareState = (): ShareState => ({
    mode: 'multi', rows: this.chartRows, cols: this.chartCols, step: this.currentDataCount, interval: this.rate
  });

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }

  private onRateChange = (nextRate: number): void => {
    this.rate = nextRate;
  };

  private onRowsChange = (nextChartRows: number): void => {
    this.chartRows = nextChartRows;
    this.currentDataCount = this.resetStep();
    this.dataProviders = getDataProvidersForDataCount(this.mochartDemoConfig.mochartConfig, this.data, this.chartRows * this.chartCols, this.currentDataCount);
    this.focusedGroupIndices = this.getFocusedGroupIndices(this.dataProviders);
  };

  private onColsChange = (nextChartCols: number): void => {
    this.chartCols = nextChartCols;
    this.currentDataCount = this.resetStep();
    this.dataProviders = getDataProvidersForDataCount(this.mochartDemoConfig.mochartConfig, this.data, this.chartRows * this.chartCols, this.currentDataCount);
    this.focusedGroupIndices = this.getFocusedGroupIndices(this.dataProviders);
  };

  private onStepBackwardClick = (): void => {
    const cycle = this.stepCycle();
    this.currentDataCount = this.mochartDemoConfig.pieMode
      ? (this.currentDataCount - 1 + cycle) % cycle
      : cycle + (this.currentDataCount - 1) % cycle;
    this.dataProviders = getDataProvidersForDataCount(this.mochartDemoConfig.mochartConfig, this.data, this.chartRows * this.chartCols, this.currentDataCount);
    this.focusedGroupIndices = this.getFocusedGroupIndices(this.dataProviders);
  };

  private onStepForwardClick = (): void => {
    this.currentDataCount = (this.currentDataCount + 1) % this.stepCycle();
    this.dataProviders = getDataProvidersForDataCount(this.mochartDemoConfig.mochartConfig, this.data, this.chartRows * this.chartCols, this.currentDataCount);
    this.focusedGroupIndices = this.getFocusedGroupIndices(this.dataProviders);
  };

  private getFocusedGroupIndices(nextDataProviders: ChartDataProviderLike[]): number[] {
    const { mochartConfig } = this.mochartDemoConfig;
    if (this.focusedGroupIndex >= 0) {
      const groupValue = this.data[this.focusedGroupIndex][mochartConfig.groupAxisConfig.property ?? ''];
      return this.getFocusedGroupIndicesForValue(nextDataProviders, groupValue);
    }
    else {
      return nextDataProviders.map(() => -1);
    }
  }

  private getFocusedGroupIndicesForValue(nextDataProviders: ChartDataProviderLike[], groupValue: unknown): number[] {
    let count: number, i: number;
    return nextDataProviders.map(dataProvider => {
      let chartGroupIndex = -1;
      const groupValues = dataProvider.getGroupValues();
      count = groupValues.length;
      for (i = 0; i < count; i++) {
        if (groupValues[i] === groupValue) {
          chartGroupIndex = i;
          break;
        }
      }
      return chartGroupIndex;
    });
  }

  private onPlayBackwardClick = (): void => {
    this.playing = true;
    this.intervalId = setInterval(this.onStepBackwardClick, this.rate);
  };

  private onPlayForwardClick = (): void => {
    this.playing = true;
    this.intervalId = setInterval(this.onStepForwardClick, this.rate);
  };

  private onStopClick = (): void => {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
    }
    this.intervalId = null;
    this.playing = false;
  };

  private onChartFocus(chartIndex: number, focusData: { focusedSeriesAxisId?: string | null; focusedSeriesId?: string | null; focusedGroupIndex?: number }): void {
    const { focusedSeriesAxisId: seriesAxisId, focusedSeriesId: seriesId } = focusData;
    let groupIndex = focusData.focusedGroupIndex;
    const { mochartConfig } = this.mochartDemoConfig;
    let nextFocusedGroupIndices = this.focusedGroupIndices;
    if (groupIndex !== undefined && groupIndex >= 0) {
      const groupValue = this.dataProviders[chartIndex].getGroupValues()[groupIndex];
      const count = this.data.length;
      for (let i = 0; i < count; i++) {
        if (this.data[i][mochartConfig.groupAxisConfig.property ?? ''] === groupValue) {
          groupIndex = i;
          break;
        }
      }
      if (groupIndex !== this.focusedGroupIndex) {
        nextFocusedGroupIndices = this.getFocusedGroupIndicesForValue(this.dataProviders, groupValue);
      }
    }
    else if (this.focusedGroupIndex >= 0) {
      nextFocusedGroupIndices = this.dataProviders.map(() => -1);
    }
    if (groupIndex !== undefined) {
      this.focusedGroupIndex = groupIndex;
    }
    if (seriesAxisId !== undefined) {
      this.focusedSeriesAxisId = seriesAxisId;
    }
    if (seriesId !== undefined) {
      this.focusedSeriesId = seriesId;
    }
    this.focusedGroupIndices = nextFocusedGroupIndices;
  }

  // The chart owns filter toggling now and reports the whole map.
  private onSeriesFilter = ({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }): void => {
    this.filteredSeriesIds = { ...nextFilteredSeriesIds };
  };

  override render(): unknown {
    const chartWidth = Math.floor((this.size.width - scrollWidthOffset) / this.chartCols);
    const chartHeight = Math.floor(this.size.height / this.chartRows);
    // Pie mode unions the stepper's per-chart suppression with the user's
    // legend filtering, so the legend stays interactive while stepping.
    const chartFilteredSeriesIds = (i: number): FilteredSeriesIds => this.mochartDemoConfig.pieMode
      ? { ...this.filteredSeriesIds, ...getPieStepSuppressedIds(this.sliceIds, i, this.currentDataCount) }
      : this.filteredSeriesIds;
    return html`<div class=${'mochart-demo-tab-container demo-layout-col chart' + (this.active ? ' active' : '')} ?inert=${!this.active}>
      <div ${ref(this.size.attach)} class="multi-charts-sizer">
        ${this.size.width > 0
          ? html`<div class="multi-charts">
              ${this.dataProviders.map((dataProvider, i) => html`<div class="multi-mochart-chart">
                ${chart({
                  mochartConfig: this.mochartDemoConfig.mochartConfig,
                  dataProvider,
                  width: chartWidth,
                  height: chartHeight,
                  filteredSeriesIds: chartFilteredSeriesIds(i),
                  focusedGroupIndex: this.focusedGroupIndices[i] ?? -1,
                  focusedSeriesAxisId: this.focusedSeriesAxisId ?? null,
                  focusedSeriesId: this.focusedSeriesId ?? null,
                  onSeriesFilter: this.onSeriesFilter,
                  onFocus: (focusData: any) => this.onChartFocus(i, focusData)
                })}
              </div>`)}
            </div>`
          : null}
      </div>
      <charts-controls .playing=${this.playing} .initialRows=${this.chartRows} .initialCols=${this.chartCols} .initialRate=${this.rate}
          .onRowsChange=${this.onRowsChange} .onColsChange=${this.onColsChange}
          .onStepBackwardClick=${this.onStepBackwardClick} .onStepForwardClick=${this.onStepForwardClick}
          .onPlayBackwardClick=${this.onPlayBackwardClick} .onPlayForwardClick=${this.onPlayForwardClick}
          .onStopClick=${this.onStopClick} .onRateChange=${this.onRateChange}
          .exportPng=${this.onExportPng} .exportSvg=${this.onExportSvg} .getShareState=${this.getShareState}></charts-controls>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'charts-tab': ChartsTab;
  }
}

// packages/mochart-demo-svelte/src/components/multi/ChartsTab.svelte
<script lang="ts">
  import { untrack, onDestroy } from 'svelte';

  import { Chart } from '@mochart/svelte';
  import { exportChartsPNG, exportChartsSVG } from '@mochart/export';

  import { getChartExportOptions, buildMochartDemoConfig, consumeShareState, getDataProvidersForDataCount, getPieSlices, getPieStepCycle, getPieStepSuppressedIds } from '@mochart/demo-common';
  import type { ShareState } from '@mochart/demo-common';

  import ChartsControls from './ChartsControls.svelte';

  import type { Demo, FilteredSeriesIds, ChartDataProviderLike } from '../../types';

  interface Props {
    demoObject: Demo;
    active?: boolean;
  }

  const scrollWidthOffset = 20;

  const defaultChartRows = 2;
  const defaultChartCols = 2;

  const defaultRate = 2000;

  let { demoObject, active = false }: Props = $props();

  function clampGrid(value: number): number {
    return Math.min(4, Math.max(1, Math.round(value)));
  }

  let intervalId: ReturnType<typeof setInterval> | null = null;
  let gridElement = $state<HTMLDivElement | null>(null);

  // A share link restores the grid size, playback step and interval; otherwise
  // start on the defaults / full data set.
  const sharedState = consumeShareState('multi');
  const shared = sharedState && sharedState.mode === 'multi' ? sharedState : null;

  const initialChartRows = shared ? clampGrid(shared.rows) : defaultChartRows;
  const initialChartCols = shared ? clampGrid(shared.cols) : defaultChartCols;
  const initialRate = shared ? shared.interval : defaultRate;

  let playing = $state(false);
  let chartRows = $state(initialChartRows);
  let chartCols = $state(initialChartCols);
  let rate = $state(initialRate);
  // Props intentionally seed local state with their initial value only; the
  // $effect.pre below re-syncs everything when the demo changes.
  // svelte-ignore state_referenced_locally
  let mochartDemoConfig = $state.raw(buildMochartDemoConfig(demoObject.config));
  // svelte-ignore state_referenced_locally
  let data = $state.raw(demoObject.data);
  // svelte-ignore state_referenced_locally
  let dataCount = $state(demoObject.data.length);
  // Pie mode steps a suppression pattern instead of data prefixes: chart i at
  // step s suppresses the last (s + i) mod cycle slices, so the grid shows
  // different-sized views of the same pie and stepping animates all charts.
  // svelte-ignore state_referenced_locally
  let sliceIds = $state.raw(mochartDemoConfig.pieMode ? getPieSlices(mochartDemoConfig.mochartConfig).map(slice => slice.id) : []);
  const stepCycle = () => mochartDemoConfig.pieMode ? getPieStepCycle(sliceIds) : dataCount;
  // A shared step seeks the playback position; otherwise start on the full set
  // (pie mode starts at step 0 — the grid's staggered initial view).
  // svelte-ignore state_referenced_locally
  let currentDataCount = $state(shared && stepCycle() > 0
    ? ((Math.round(shared.step) % stepCycle()) + stepCycle()) % stepCycle()
    : (mochartDemoConfig.pieMode ? 0 : demoObject.data.length));
  // svelte-ignore state_referenced_locally
  let dataProviders = $state.raw(getDataProvidersForDataCount(
    mochartDemoConfig.mochartConfig, demoObject.data, initialChartRows * initialChartCols, currentDataCount));
  // svelte-ignore state_referenced_locally
  let focusedGroupIndices = $state.raw<number[]>(dataProviders.map(() => -1));
  let focusedGroupIndex = $state(-1);
  let focusedSeriesAxisId = $state.raw<string | null>(null);
  let focusedSeriesId = $state.raw<string | null>(null);
  let filteredSeriesIds = $state.raw<FilteredSeriesIds>({});

  function initFocusAndFiltered() {
    focusedGroupIndex = -1;
    focusedSeriesAxisId = null;
    focusedSeriesId = null;
    filteredSeriesIds = {};
  }

  // svelte-ignore state_referenced_locally
  let previousDemoObject = demoObject;
  // svelte-ignore state_referenced_locally
  let previousActive = active;
  $effect.pre(() => {
    const nextDemoObject = demoObject;
    const nextActive = active;
    untrack(() => {
      if (nextDemoObject !== previousDemoObject) {
        previousDemoObject = nextDemoObject;
        mochartDemoConfig = buildMochartDemoConfig(nextDemoObject.config);
        initFocusAndFiltered();
        playing = false;
        data = nextDemoObject.data;
        dataCount = data.length;
        sliceIds = mochartDemoConfig.pieMode ? getPieSlices(mochartDemoConfig.mochartConfig).map(slice => slice.id) : [];
        currentDataCount = resetStep();
        dataProviders = getDataProvidersForDataCount(mochartDemoConfig.mochartConfig, data, chartRows * chartCols, currentDataCount);
        focusedGroupIndices = dataProviders.map(() => -1);
      }
      if (nextActive !== previousActive) {
        previousActive = nextActive;
        onStopClick();
      }
    });
  });

  function onRateChange(nextRate: number) {
    rate = nextRate;
  }

  function resetStep(): number {
    return mochartDemoConfig.pieMode ? 0 : dataCount;
  }

  function onRowsChange(nextChartRows: number) {
    chartRows = nextChartRows;
    currentDataCount = resetStep();
    dataProviders = getDataProvidersForDataCount(mochartDemoConfig.mochartConfig, data, chartRows * chartCols, currentDataCount);
    focusedGroupIndices = getFocusedGroupIndices(dataProviders);
  }

  function onColsChange(nextChartCols: number) {
    chartCols = nextChartCols;
    currentDataCount = resetStep();
    dataProviders = getDataProvidersForDataCount(mochartDemoConfig.mochartConfig, data, chartRows * chartCols, currentDataCount);
    focusedGroupIndices = getFocusedGroupIndices(dataProviders);
  }

  function onStepBackwardClick() {
    const cycle = stepCycle();
    currentDataCount = mochartDemoConfig.pieMode
      ? (currentDataCount - 1 + cycle) % cycle
      : cycle + (currentDataCount - 1) % cycle;
    dataProviders = getDataProvidersForDataCount(mochartDemoConfig.mochartConfig, data, chartRows * chartCols, currentDataCount);
    focusedGroupIndices = getFocusedGroupIndices(dataProviders);
  }

  function onStepForwardClick() {
    currentDataCount = (currentDataCount + 1) % stepCycle();
    dataProviders = getDataProvidersForDataCount(mochartDemoConfig.mochartConfig, data, chartRows * chartCols, currentDataCount);
    focusedGroupIndices = getFocusedGroupIndices(dataProviders);
  }

  function getFocusedGroupIndices(nextDataProviders: ChartDataProviderLike[]): number[] {
    const { mochartConfig } = mochartDemoConfig;
    if (focusedGroupIndex >= 0) {
      const groupValue = data[focusedGroupIndex][mochartConfig.groupAxisConfig.property ?? ''];
      return getFocusedGroupIndicesForValue(nextDataProviders, groupValue);
    }
    else {
      return nextDataProviders.map(() => -1);
    }
  }

  function getFocusedGroupIndicesForValue(nextDataProviders: ChartDataProviderLike[], groupValue: unknown): number[] {
    let count, i;
    return nextDataProviders.map(dataProvider => {
      let chartGroupIndex = -1;
      const groupValues = dataProvider.getGroupValues();
      count = groupValues.length;
      for (i = 0; i < count; i++) {
        if (groupValues[i] === groupValue) {
          chartGroupIndex = i;
          break;
        }
      }
      return chartGroupIndex;
    });
  }

  function onPlayBackwardClick() {
    playing = true;
    intervalId = setInterval(onStepBackwardClick, rate);
  }

  function onPlayForwardClick() {
    playing = true;
    intervalId = setInterval(onStepForwardClick, rate);
  }

  function onStopClick() {
    if (intervalId !== null) {
      clearInterval(intervalId);
    }
    intervalId = null;
    playing = false;
  }

  onDestroy(() => {
    if (intervalId !== null) {
      clearInterval(intervalId);
      intervalId = null;
    }
  });

  function onChartFocus(chartIndex: number, focusData: { focusedSeriesAxisId?: string | null; focusedSeriesId?: string | null; focusedGroupIndex?: number }) {
    const { focusedSeriesAxisId: seriesAxisId, focusedSeriesId: seriesId } = focusData;
    let groupIndex = focusData.focusedGroupIndex;
    const { mochartConfig } = mochartDemoConfig;
    let nextFocusedGroupIndices = focusedGroupIndices;
    if (groupIndex !== undefined && groupIndex >= 0) {
      const groupValue = dataProviders[chartIndex].getGroupValues()[groupIndex];
      let i, count = data.length;
      for (i = 0; i < count; i++) {
        if (data[i][mochartConfig.groupAxisConfig.property ?? ''] === groupValue) {
          groupIndex = i;
          break;
        }
      }
      if (groupIndex !== focusedGroupIndex) {
        nextFocusedGroupIndices = getFocusedGroupIndicesForValue(dataProviders, groupValue);
      }
    }
    else if (focusedGroupIndex >= 0) {
      nextFocusedGroupIndices = dataProviders.map(() => -1);
    }
    if (groupIndex !== undefined) {
      focusedGroupIndex = groupIndex;
    }
    if (seriesAxisId !== undefined) {
      focusedSeriesAxisId = seriesAxisId;
    }
    if (seriesId !== undefined) {
      focusedSeriesId = seriesId;
    }
    focusedGroupIndices = nextFocusedGroupIndices;
  }

  // The chart owns filter toggling now and reports the whole map.
  function onSeriesFilter({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }) {
    filteredSeriesIds = { ...nextFilteredSeriesIds };
  }

  // The whole grid exports as one tiled image; share captures the grid size,
  // playback step and interval so the link restores the same view.
  function getChartContainers(): Element[] {
    return gridElement ? Array.from(gridElement.querySelectorAll('.multi-mochart-chart')) : [];
  }

  function onExportPng() {
    const containers = getChartContainers();
    if (containers.length > 0) {
      void exportChartsPNG(containers, { cols: chartCols, ...getChartExportOptions() });
    }
  }

  function onExportSvg() {
    const containers = getChartContainers();
    if (containers.length > 0) {
      exportChartsSVG(containers, { cols: chartCols, ...getChartExportOptions() });
    }
  }

  function getShareState(): ShareState {
    return { mode: 'multi', rows: chartRows, cols: chartCols, step: currentDataCount, interval: rate };
  }

  // Measured size of the charts grid.
  let gridWidth = $state(0);
  let gridHeight = $state(0);

  const chartWidth = $derived(Math.floor((gridWidth - scrollWidthOffset) / chartCols));
  const chartHeight = $derived(Math.floor(gridHeight / chartRows));
</script>

<div class={"mochart-demo-tab-container demo-layout-col chart" + (active ? " active" : "")} inert={!active}>
  <div class="multi-charts-sizer" bind:this={gridElement} bind:clientWidth={gridWidth} bind:clientHeight={gridHeight}>
    {#if gridWidth > 0}
      <div class="multi-charts">
        {#each dataProviders as dataProvider, i (i)}
          <div class="multi-mochart-chart">
            <!-- Pie mode unions the stepper's per-chart suppression with the
                 user's legend filtering, so the legend stays interactive while
                 stepping. -->
            <Chart mochartConfig={mochartDemoConfig.mochartConfig} {dataProvider}
                   width={chartWidth} height={chartHeight}
                   filteredSeriesIds={mochartDemoConfig.pieMode
                     ? { ...filteredSeriesIds, ...getPieStepSuppressedIds(sliceIds, i, currentDataCount) }
                     : filteredSeriesIds}
                   focusedGroupIndex={focusedGroupIndices[i] ?? -1}
                   focusedSeriesAxisId={focusedSeriesAxisId ?? null} focusedSeriesId={focusedSeriesId ?? null}
                   {onSeriesFilter} onFocus={(focusData) => onChartFocus(i, focusData)} />
          </div>
        {/each}
      </div>
    {/if}
  </div>
  <ChartsControls {playing} initialRows={initialChartRows} initialCols={initialChartCols} {initialRate}
                  {onRowsChange} {onColsChange}
                  {onStepBackwardClick} {onStepForwardClick}
                  {onPlayBackwardClick} {onPlayForwardClick}
                  {onStopClick} {onRateChange}
                  exportPng={onExportPng} exportSvg={onExportSvg} {getShareState} />
</div>
