// packages/mochart-svelte/src/Chart.svelte
<script lang="ts">
  // Svelte wrapper around mochart's `createChart`: takes an enhanced config
  // (`mochartConfig`) and a data provider. Omit `width`/`height` to have the
  // chart track the container div's size.
  import { createChart } from '@mochart/core';
  import ChartHost from './ChartHost.svelte';
  import type { ChartProps } from './types';

  let props: ChartProps = $props();
</script>

<ChartHost create={createChart} {...props} />

// packages/mochart-react/src/Chart.tsx
import { createChart } from '@mochart/core';
import type { ReactElement } from 'react';
import { useChartHost } from './useChartHost.js';
import type { ChartProps } from './types.js';

/**
 * React wrapper around mochart's `createChart`: takes an enhanced config
 * (`mochartConfig`) and a data provider. Omit `width`/`height` to have the
 * chart track the container div's size.
 */
export default function Chart(props: ChartProps): ReactElement {
  const { className, style, ...chartProps } = props;
  const containerRef = useChartHost(createChart, chartProps);
  return <div ref={containerRef} className={className} style={{ width: props.width, height: props.height, ...style }} />;
}
