// packages/mochart-angular/src/types.ts
import type { Type } from '@angular/core';
import type { DataProvider, MochartConfig } from '@mochart/core';

/** Props mochart passes to placeholder components (loading, error, and empty states). */
export interface PlaceholderProps {
  width?: number;
  height?: number;
  mochartConfig?: MochartConfig | null;
  dataProvider?: DataProvider<unknown> | null;
  error?: unknown;
  hasData?: boolean;
}

/**
 * An Angular component rendered for one of the chart's placeholder states.
 * The chart context (`width`, `height`, `error`, …) is applied to whichever
 * of the `PlaceholderProps` names the component declares as inputs.
 */
export type PlaceholderComponent = Type<unknown>;

// packages/mochart-react/src/types.ts
import type { ComponentType, CSSProperties } from 'react';

/** Props mochart passes to placeholder components (loading, error, and empty states). */
export interface PlaceholderProps {
  width?: number;
  height?: number;
  mochartConfig?: any;
  dataProvider?: any;
  error?: any;
  hasData?: boolean;
}

/** A React component rendered for one of the chart's placeholder states. */
export type PlaceholderComponent = ComponentType<PlaceholderProps>;

export interface ChartCallbackProps {
  onChartClick?: (eventPayload: any) => void;
  onChartMouseEnter?: (eventPayload: any) => void;
  onChartMouseMove?: (eventPayload: any) => void;
  onChartMouseLeave?: (eventPayload: any) => void;
  onTitleClick?: (eventPayload: any) => void;
  onFocus?: (focusData: any) => void;
  onSeriesFilter?: (filterData: any) => void;
  onSeriesLayoutInfoChange?: (bounds: any) => void;
  loadingComponent?: PlaceholderComponent;
  errorComponent?: PlaceholderComponent;
  noDataComponent?: PlaceholderComponent;
  noSizeComponent?: PlaceholderComponent;
  noSeriesComponent?: PlaceholderComponent;
  configErrorComponent?: PlaceholderComponent;
}

export interface BaseChartProps extends ChartCallbackProps {
  /** Explicit pixel width; omit to track the container element's width. */
  width?: number;
  /** Explicit pixel height; omit to track the container element's height. */
  height?: number;
  /** Class applied to the container div the chart mounts into. */
  className?: string;
  /** Style applied to the container div the chart mounts into. */
  style?: CSSProperties;
  loading?: boolean;
  error?: any;
}

/** Props for `Chart`: a pre-enhanced config plus a data provider. */
export interface ChartProps extends BaseChartProps {
  mochartConfig: any;
  dataProvider: any;
}

/** Props for `DefaultChart`: a raw config plus a plain array-of-objects dataset. */
export interface DefaultChartProps extends BaseChartProps {
  config: any;
  data: any[];
}
