// packages/mochart-demo-lit/src/components/transition/transition-chart-tab.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { PropertyValues } from 'lit';

import { chart } from 'mochart-lit';
import type { MochartConfig } from 'mochart';

import { LightElement } from '../misc/LightElement';
import { buttonWithTooltip, icon } from '../misc/templates';

import type { ChartDataProviderLike } from '../../types';

@customElement('transition-chart-tab')
export class TransitionChartTab extends LightElement {
  @property({ attribute: false }) active = false;
  @property({ attribute: false }) mochartConfig!: MochartConfig;
  @property({ attribute: false }) dataProviders: ChartDataProviderLike[] = [];

  @state() private dataProviderIndex = 0;

  override willUpdate(changed: PropertyValues<this>): void {
    if (this.hasUpdated && (changed.has('mochartConfig') || changed.has('dataProviders'))) {
      this.dataProviderIndex = 0;
    }
  }

  private onStepBack = (): void => {
    if (this.dataProviders.length > 1) {
      if (this.dataProviderIndex === 0) {
        this.dataProviderIndex = this.dataProviders.length - 1;
      }
      else {
        this.dataProviderIndex--;
      }
    }
  };

  private onStepForward = (): void => {
    if (this.dataProviders.length > 1) {
      if (this.dataProviderIndex === this.dataProviders.length - 1) {
        this.dataProviderIndex = 0;
      }
      else {
        this.dataProviderIndex++;
      }
    }
  };

  override render(): unknown {
    return html`<div class=${'mochart-demo-tab-container col chart' + (this.active ? ' active' : '')}>
      <div class="transition-chart-sizer">
        ${chart({
          style: 'flex: 1 1 auto; min-width: 0; min-height: 0; overflow: hidden;',
          mochartConfig: this.mochartConfig,
          dataProvider: this.dataProviders[this.dataProviderIndex]
        })}
      </div>
      <div class="transition-controls">
        <form class="form-inline">
          <div class="form-group">
            <div class="btn-toolbar" role="toolbar">
              <div class="btn-group">
                ${buttonWithTooltip(
                  { id: 'transition-back', label: 'Back', tooltipText: 'Transition to the previous dataset', tooltipPlacement: 'top-start', onClick: this.onStepBack, ariaLabel: 'Step Backward' },
                  icon({ size: 'lg', fixedWidth: true, name: 'backward-step' })
                )}
                ${buttonWithTooltip(
                  { id: 'transition-forward', label: 'Next', tooltipText: 'Transition to the next dataset', tooltipPlacement: 'top-start', onClick: this.onStepForward, ariaLabel: 'Step Forward' },
                  icon({ size: 'lg', fixedWidth: true, name: 'forward-step' })
                )}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'transition-chart-tab': TransitionChartTab;
  }
}

// packages/mochart-demo-svelte/src/components/transition/TransitionChartTab.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  import { Chart } from 'mochart-svelte';
  import type { MochartConfig } from 'mochart';

  import ButtonWithTooltip from '../misc/ButtonWithTooltip.svelte';
  import Icon from '../misc/Icon.svelte';

  import type { ChartDataProviderLike } from '../../types';

  interface Props {
    active?: boolean;
    mochartConfig: MochartConfig;
    dataProviders: ChartDataProviderLike[];
  }

  let { active = false, mochartConfig, dataProviders }: Props = $props();

  let dataProviderIndex = $state(0);

  let previousMochartConfig = mochartConfig;
  let previousDataProviders = dataProviders;
  $effect.pre(() => {
    const nextMochartConfig = mochartConfig;
    const nextDataProviders = dataProviders;
    untrack(() => {
      if (nextMochartConfig !== previousMochartConfig || nextDataProviders !== previousDataProviders) {
        previousMochartConfig = nextMochartConfig;
        previousDataProviders = nextDataProviders;
        dataProviderIndex = 0;
      }
    });
  });

  function onStepBack() {
    if (dataProviders.length > 1) {
      if (dataProviderIndex === 0) {
        dataProviderIndex = dataProviders.length - 1;
      }
      else {
        dataProviderIndex--;
      }
    }
  }

  function onStepForward() {
    if (dataProviders.length > 1) {
      if (dataProviderIndex === dataProviders.length - 1) {
        dataProviderIndex = 0;
      }
      else {
        dataProviderIndex++;
      }
    }
  }
</script>

<div class={"mochart-demo-tab-container col chart" + (active ? " active" : "")}>
  <div class="transition-chart-sizer">
    <Chart style="flex: 1 1 auto; min-width: 0; min-height: 0; overflow: hidden;"
           {mochartConfig} dataProvider={dataProviders[dataProviderIndex]} />
  </div>
  <div class="transition-controls">
    <form class="form-inline">
      <div class="form-group">
        <div class="btn-toolbar" role="toolbar">
          <div class="btn-group">
            <ButtonWithTooltip id="transition-back" label="Back" tooltipText="Transition to the previous dataset" tooltipPlacement="top-start"
                               onClick={onStepBack} aria-label="Step Backward">
              <Icon size="lg" fixedWidth={true} name="backward-step" />
            </ButtonWithTooltip>
            <ButtonWithTooltip id="transition-forward" label="Next" tooltipText="Transition to the next dataset" tooltipPlacement="top-start"
                               onClick={onStepForward} aria-label="Step Forward">
              <Icon size="lg" fixedWidth={true} name="forward-step" />
            </ButtonWithTooltip>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
