// packages/mochart-demo-angular/src/components/misc/notes-menu-item.ts
import { Component, Input, signal } from '@angular/core';
import type { OnChanges } from '@angular/core';

import { demoText } from '@mochart/demo-common';

import { Icon } from './icon';

/** `aria-controls` has to point at an id, and ids have to be unique. */
let disclosureIdCounter = 0;

/**
 * The phone fold's stand-in for the NotesMenu popover: a `.demo-menu-item` row
 * that expands the same title and body inline, inside the navigation row's
 * overflow panel. `.demo-menu-keep-open` so revealing the note does not also
 * dismiss the menu it lives in; the panel's own `overflow-y: auto` under its
 * `max-height` is what makes a long note readable on a screen that does not
 * scroll.
 */
@Component({
  selector: 'app-notes-menu-item',
  imports: [Icon],
  styles: [':host { display: contents; }'],
  template: `
    <div class="mochart-demo-notes-item demo-menu-keep-open">
      <button type="button" class="demo-menu-item"
              [attr.title]="text.trigger.tooltip"
              [attr.aria-expanded]="expanded()" [attr.aria-controls]="disclosureId"
              (click)="expanded.set(!expanded())">
        <app-icon [fixedWidth]="true" name="circle-info" /> <span class="mochart-menu-item-label">{{ text.trigger.aria }}</span>
        <app-icon [fixedWidth]="true" [name]="expanded() ? 'chevron-up' : 'chevron-down'" iconStyle="margin-left: auto;" />
      </button>
      <div class="demo-field" [id]="disclosureId" [hidden]="!expanded()">
        <span class="demo-menu-notes-title">{{ demoTitle }}</span>
        <span class="demo-menu-notes-body">{{ notes }}</span>
      </div>
    </div>
  `
})
export class NotesMenuItem implements OnChanges {
  readonly text = demoText.demoNotes;

  @Input({ required: true }) demoTitle!: string;
  @Input() notes?: string;

  readonly expanded = signal(false);
  readonly disclosureId = 'demo-notes-disclosure-a' + ++disclosureIdCounter;

  // A different demo's notes start collapsed again (history navigation).
  ngOnChanges(): void {
    this.expanded.set(false);
  }
}

// packages/mochart-demo-lit/src/components/misc/notes-menu-item.ts
import { html, nothing } from 'lit';
import type { PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';

import { demoText } from '@mochart/demo-common';

import { LightElement } from './LightElement';
import { icon } from './templates';

/** `aria-controls` has to point at an id, and ids have to be unique. */
let disclosureIdCounter = 0;

/**
 * The phone fold's stand-in for the NotesMenu popover: a `.demo-menu-item` row
 * that expands the same title and body inline, inside the navigation row's
 * overflow panel. A popover cannot come along into the fold — its panel would
 * be a descendant of an element the menu hides with `display: none` — so
 * TopBar renders this instead below the breakpoint.
 *
 * `.demo-menu-keep-open` so revealing the note does not also dismiss the menu
 * it lives in; the panel's own `overflow-y: auto` under its `max-height` is
 * what makes a long note readable on a screen that does not scroll.
 */
@customElement('notes-menu-item')
export class NotesMenuItem extends LightElement {
  @property({ attribute: false }) demoTitle = '';
  @property({ attribute: false }) notes?: string;

  @state() private expanded = false;

  private readonly disclosureId = 'demo-notes-disclosure-l' + ++disclosureIdCounter;

  // A different demo's notes start collapsed again (history navigation).
  override willUpdate(changed: PropertyValues<this>): void {
    if (this.hasUpdated && (changed.has('demoTitle') || changed.has('notes'))) {
      this.expanded = false;
    }
  }

  override render(): unknown {
    if (this.notes === undefined) {
      return nothing;
    }
    return html`<div class="mochart-demo-notes-item demo-menu-keep-open">
      <button type="button" class="demo-menu-item"
              title=${demoText.demoNotes.trigger.tooltip}
              aria-expanded=${String(this.expanded)} aria-controls=${this.disclosureId}
              @click=${() => { this.expanded = !this.expanded; }}>${icon({ fixedWidth: true, name: 'circle-info' })} <span class="mochart-menu-item-label">${demoText.demoNotes.trigger.aria}</span>${icon({ fixedWidth: true, name: this.expanded ? 'chevron-up' : 'chevron-down', style: 'margin-left: auto;' })}</button>
      <div class="demo-field" id=${this.disclosureId} ?hidden=${!this.expanded}>
        <span class="demo-menu-notes-title">${this.demoTitle}</span>
        <span class="demo-menu-notes-body">${this.notes}</span>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'notes-menu-item': NotesMenuItem;
  }
}
