// packages/mochart-demo-svelte/src/components/sparkline/DemoSparkline.svelte
<script module lang="ts">
  import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';

  const text = demoText.sparklinePage;
</script>

<script lang="ts">
  import { DefaultChart } from '@mochart/svelte';

  import BackToDemosButton from '../misc/BackToDemosButton.svelte';
  import ButtonWithTooltip from '../misc/ButtonWithTooltip.svelte';
  import Icon from '../misc/Icon.svelte';
  import SiteRootButton from '../misc/SiteRootButton.svelte';
  import ThemeToggleButton from '../misc/ThemeToggleButton.svelte';

  interface Props {
    siteRootUrl?: string;
    onBackToDemos: () => void;
  }

  let { siteRootUrl = undefined, onBackToDemos }: Props = $props();

  // The Randomize button advances the step; every metric's dataset is a pure
  // function of it, so the charts and "Latest" cells all re-derive together.
  let step = $state(0);

  const inlineData = $derived(inlineSparklineMetrics.map(metric => metric.generate(step)));
  const tableData = $derived(tableSparklineMetrics.map(metric => metric.generate(step)));

  function onRandomize() {
    step++;
  }
</script>

<div class="mochart-demo-container">
  <div class="mochart-demo-tabs-container">
    <div class="mochart-demo-nav-group">
      <SiteRootButton {siteRootUrl} />
      <BackToDemosButton {onBackToDemos} />
    </div>
    <ThemeToggleButton />
  </div>
  <div class="sparkline-page">
    <p class="sparkline-intro">
      {#each text.intro as segment, i (i)}
        {segment}{#if inlineSparklineMetrics[i] !== undefined}<span class="sparkline-inline"><DefaultChart
          config={inlineSparklineMetrics[i].config} data={inlineData[i]}
          width={inlineSparklineMetrics[i].width} height={inlineSparklineMetrics[i].height} /></span>{/if}
      {/each}
    </p>
    <div class="sparkline-controls">
      <ButtonWithTooltip id="sparkline-randomize" label={text.randomize.label} color="primary"
                         tooltipText={text.randomize.tooltip} tooltipPlacement="top-start"
                         onClick={onRandomize} aria-label={text.randomize.aria}>
        <Icon fixedWidth={true} name="dice" />
      </ButtonWithTooltip>
    </div>
    <table class="sparkline-table">
      <thead>
        <tr>
          <th>{text.table.metric}</th>
          <th>{text.table.latest}</th>
          <th>{text.table.trend}</th>
        </tr>
      </thead>
      <tbody>
        {#each tableSparklineMetrics as metric, i (metric.id)}
          <tr>
            <td>{metric.label}</td>
            <td class="sparkline-value">{metric.latestText(tableData[i])}</td>
            <td class="sparkline-cell">
              <DefaultChart config={metric.config} data={tableData[i]}
                            width={metric.width} height={metric.height} />
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

// packages/mochart-demo-vue/src/components/sparkline/DemoSparkline.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { DefaultChart } from '@mochart/vue';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';

import BackToDemosButton from '../misc/BackToDemosButton.vue';
import ButtonWithTooltip from '../misc/ButtonWithTooltip.vue';
import Icon from '../misc/Icon.vue';
import SiteRootButton from '../misc/SiteRootButton.vue';
import ThemeToggleButton from '../misc/ThemeToggleButton.vue';

interface Props {
  siteRootUrl?: string;
  onBackToDemos: () => void;
}

const props = defineProps<Props>();

const text = demoText.sparklinePage;

// The Randomize button steps every metric's dataset in lockstep; each chart's
// data (and each table row's latest text) is derived from the current step.
const step = ref(0);

const inlineData = computed(() => inlineSparklineMetrics.map(metric => metric.generate(step.value)));
const tableData = computed(() => tableSparklineMetrics.map(metric => metric.generate(step.value)));

function onRandomize() {
  step.value++;
}
</script>

<template>
  <div class="mochart-demo-container">
    <div class="mochart-demo-tabs-container">
      <div class="mochart-demo-nav-group">
        <SiteRootButton :site-root-url="props.siteRootUrl" />
        <BackToDemosButton :on-back-to-demos="props.onBackToDemos" />
      </div>
      <ThemeToggleButton />
    </div>
    <div class="sparkline-page">
      <!-- The intro paragraph: copy segments with the inline metrics between
           them. Keep {{ segment }} and the span adjacent so the segments'
           built-in spacing survives template whitespace condensing. -->
      <p class="sparkline-intro">
        <template v-for="(segment, i) in text.intro" :key="i">{{ segment }}<span v-if="inlineSparklineMetrics[i] !== undefined" class="sparkline-inline">
          <DefaultChart :config="inlineSparklineMetrics[i].config" :data="inlineData[i]"
                        :width="inlineSparklineMetrics[i].width" :height="inlineSparklineMetrics[i].height" />
        </span></template>
      </p>
      <div class="sparkline-controls">
        <ButtonWithTooltip id="sparkline-randomize" color="primary" :label="text.randomize.label"
                           :tooltip-text="text.randomize.tooltip" :on-click="onRandomize"
                           :aria-label="text.randomize.aria">
          <Icon :fixed-width="true" name="dice" />
        </ButtonWithTooltip>
      </div>
      <table class="sparkline-table">
        <thead>
          <tr>
            <th>{{ text.table.metric }}</th>
            <th>{{ text.table.latest }}</th>
            <th>{{ text.table.trend }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(metric, i) in tableSparklineMetrics" :key="metric.id">
            <td>{{ metric.label }}</td>
            <td class="sparkline-value">{{ metric.latestText(tableData[i]) }}</td>
            <td class="sparkline-cell">
              <DefaultChart :config="metric.config" :data="tableData[i]"
                            :width="metric.width" :height="metric.height" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
