// packages/mochart-demo-svelte/src/components/misc/ErrorTab.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  import { demoText } from '@mochart/demo-common';

  // Error-boundary equivalent of the react ErrorTab. Unlike the react
  // version (which cloned its child to inject `active`), children here
  // receive their `active` prop directly at the call site.
  interface Props {
    active: boolean;
    children: Snippet;
  }

  let { active, children }: Props = $props();
</script>

<svelte:boundary onerror={(error) => console.error(error)}>
  {@render children()}

  {#snippet failed()}
    <div class={"mochart-demo-tab-container error" + (active ? " active" : "")}>
      <div class="alert alert-danger text-center mochart-demo-error-message" role="alert">
        {demoText.errors.errorOccurred}
      </div>
    </div>
  {/snippet}
</svelte:boundary>

// packages/mochart-demo-react/src/components/misc/ErrorTab.tsx
import React, { Component, type ErrorInfo, type ReactElement } from 'react';

import { demoText } from '@mochart/demo-common';

interface Props {
  active: boolean;
  // The single child receives `active` injected via cloneElement.
  children: ReactElement<any>;
}

interface State {
  hasError: boolean;
}

// Error boundaries have no hook equivalent, so this stays a class component.
export default class ErrorTab extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidCatch(error: Error, info: ErrorInfo) {
    console.error(error, info);
    this.setState({ hasError: true });
  }

  render() {
    const { active } = this.props;
    const { hasError } = this.state;
    if (hasError) {
      return (
        <div className={"mochart-demo-tab-container error" + (active ? " active" : "")}>
          <div className="alert alert-danger text-center mochart-demo-error-message" role="alert">
            {demoText.errors.errorOccurred}
          </div>
        </div>
      );
    }
    else {
      return React.cloneElement(this.props.children, { active });
    }
  }
}
