// packages/mochart-demo-angular/src/components/single/chart-tab.ts
import { Component, ElementRef, Input, ViewChild, signal } from '@angular/core';
import type { AfterViewInit, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';

import { hasConfigStructureChange } from '@mochart/core';

import buildMochartDemoConfig from '../../config/mochartDemoConfig';

import { EditableChart } from './editable-chart';
import { createElementSize } from '../misc/element-size';

import type { DemoConfig, DataRow, MochartDemoConfig, FocusData, FilteredSeriesIds } from '../../types';

const minChartWidthForSecondChart = 480;
const scrollWidthOffset = 20;
const defaultChartCount = 1;

@Component({
  selector: 'app-chart-tab',
  imports: [EditableChart],
  styles: [':host { display: contents; }'],
  template: `
    <div #container [class]="'mochart-demo-tab-container row chart' + (active ? ' active' : '')">
      <div class="editable-charts-sizer">
        <div class="editable-charts">
          @if (mochartDemoConfig() && width() > 0) {
            @for (i of chartIndexes; track i) {
              <app-editable-chart [chartCount]="chartCount()" [showChartCountControls]="allowedChartCount > 1 && i === 1"
                                  [width]="chartWidth" [mochartDemoConfig]="mochartDemoConfig()!" [data]="data ?? []" [dataError]="dataError"
                                  [isActive]="active" [filteredSeriesIds]="filteredSeriesIds()" [focusedGroupIndex]="focusedGroupIndex()"
                                  [focusedSeriesAxisId]="focusedSeriesAxisId()" [focusedSeriesId]="focusedSeriesId()" [onChartCountToggle]="onChartCountToggle"
                                  [onFocus]="onFocus" [onSeriesFilter]="onSeriesFilter" />
            }
          }
        </div>
      </div>
    </div>
  `
})
export class ChartTab implements OnInit, OnChanges, AfterViewInit, OnDestroy {
  @Input() config: DemoConfig | null = null;
  @Input() data: DataRow[] | null = null;
  @Input() dataError: string | boolean | null = false;
  @Input() active = false;

  @ViewChild('container', { static: true }) containerElement!: ElementRef<HTMLDivElement>;

  // Measured width of the tab (the react demo wrapped this tab in the
  // react-sizer HOC for the same purpose).
  private elementSize = createElementSize();
  width = this.elementSize.width;

  chartCount = signal(defaultChartCount);
  focusedSeriesAxisId = signal<string | null>(null);
  focusedSeriesId = signal<string | null>(null);
  focusedGroupIndex = signal(-1);
  filteredSeriesIds = signal<FilteredSeriesIds>({});
  mochartDemoConfig = signal<MochartDemoConfig | null>(null);

  ngOnInit(): void {
    this.mochartDemoConfig.set(this.config ? buildMochartDemoConfig(this.config) : null);
  }

  ngAfterViewInit(): void {
    this.elementSize.observe(this.containerElement.nativeElement);
  }

  ngOnDestroy(): void {
    this.elementSize.disconnect();
  }

  private resetFocusAndFiltered(): void {
    this.focusedSeriesAxisId.set(null);
    this.focusedSeriesId.set(null);
    this.focusedGroupIndex.set(-1);
    this.filteredSeriesIds.set({});
  }

  // Mirror the react lifecycle: a config change rebuilds the demo config and
  // resets focus/filter state when the structure changed (or on data errors);
  // a data change remaps the focused group index onto the new data.
  ngOnChanges(changes: SimpleChanges): void {
    const configChange = changes['config'];
    const dataChange = changes['data'];
    const dataErrorChange = changes['dataError'];
    if (!configChange && !dataChange && !dataErrorChange) {
      return;
    }
    if ([configChange, dataChange, dataErrorChange].some(change => change?.firstChange)) {
      return;
    }
    if (this.dataError || configChange) {
      let configChanged = false;
      if (configChange) {
        const nextDemoConfig = this.config ? buildMochartDemoConfig(this.config) : null;
        const currentDemoConfig = this.mochartDemoConfig();
        if (nextDemoConfig && currentDemoConfig) {
          configChanged = hasConfigStructureChange(currentDemoConfig.mochartConfig, nextDemoConfig.mochartConfig);
        }
        this.mochartDemoConfig.set(nextDemoConfig);
      }
      if (this.dataError || configChanged) {
        this.resetFocusAndFiltered();
      }
    }
    else if (dataChange) {
      const previousData = dataChange.previousValue as DataRow[] | null;
      const previousDataError = dataErrorChange ? dataErrorChange.previousValue : this.dataError;
      const { configValidation, mochartConfig } = this.mochartDemoConfig() ?? {};
      const valid = configValidation?.valid ?? false;
      if (!previousDataError && previousData && this.data && valid && mochartConfig) {
        if (this.focusedGroupIndex() >= 0) {
          const property = mochartConfig.groupAxisConfig.property ?? '';
          const groupValue = previousData[this.focusedGroupIndex()][property];
          let newFocusedGroupIndex = -1;
          let i, count = this.data.length;
          for (i = 0; i < count; i++) {
            if (this.data[i][property] === groupValue) {
              newFocusedGroupIndex = i;
              break;
            }
          }
          this.focusedGroupIndex.set(newFocusedGroupIndex);
        }
      }
      else {
        this.resetFocusAndFiltered();
      }
    }
  }

  onFocus = (focusData: FocusData = {}): void => {
    const { seriesAxisId, seriesId, groupIndex } = focusData;
    if (seriesAxisId !== void 0) {
      this.focusedSeriesAxisId.set(seriesAxisId);
    }
    if (seriesId !== void 0) {
      this.focusedSeriesId.set(seriesId);
    }
    if (groupIndex !== void 0) {
      this.focusedGroupIndex.set(groupIndex);
    }
  };

  // The chart owns filter toggling now and reports the whole map.
  onSeriesFilter = ({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }): void => {
    this.filteredSeriesIds.set({ ...nextFilteredSeriesIds });
  };

  onChartCountToggle = (): void => {
    this.chartCount.set(this.chartCount() === 1 ? 2 : 1);
  };

  get allowedChartCount(): number {
    return Math.floor(this.width() / 2) > minChartWidthForSecondChart ? 2 : 1;
  }

  get adjustedChartCount(): number {
    return Math.min(this.chartCount(), this.allowedChartCount);
  }

  get chartWidth(): number {
    return Math.floor((this.width() - scrollWidthOffset) / this.adjustedChartCount);
  }

  get chartIndexes(): number[] {
    return Array.from({ length: this.adjustedChartCount }, (_, index) => index + 1);
  }
}

// packages/mochart-demo-svelte/src/components/single/ChartTab.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  import { hasConfigStructureChange } from 'mochart';

  import buildMochartDemoConfig from '../../config/mochartDemoConfig';

  import EditableChart from './EditableChart.svelte';

  import type { DemoConfig, DataRow, MochartDemoConfig, FocusData, FilteredSeriesIds } from '../../types';

  interface Props {
    config?: DemoConfig | null;
    data?: DataRow[] | null;
    dataError?: string | boolean | null;
    active?: boolean;
  }

  const minChartWidthForSecondChart = 480;
  const scrollWidthOffset = 20;
  const defaultChartCount = 1;

  let { config = null, data = null, dataError = false, active = false }: Props = $props();

  // Measured width of the tab (the react demo wrapped this tab in the
  // react-sizer HOC for the same purpose).
  let width = $state(0);

  let chartCount = $state(defaultChartCount);
  let focusedSeriesAxisId = $state.raw<string | null>(null);
  let focusedSeriesId = $state.raw<string | null>(null);
  let focusedGroupIndex = $state(-1);
  let filteredSeriesIds = $state.raw<FilteredSeriesIds>({});
  let mochartDemoConfig = $state.raw<MochartDemoConfig | null>(config ? buildMochartDemoConfig(config) : null);

  function resetFocusAndFiltered() {
    focusedSeriesAxisId = null;
    focusedSeriesId = null;
    focusedGroupIndex = -1;
    filteredSeriesIds = {};
  }

  // Mirror the react lifecycle: a config change rebuilds the demo config and
  // resets focus/filter state when the structure changed (or on data errors);
  // a data change remaps the focused group index onto the new data.
  let previousConfig = config;
  let previousData = data;
  let previousDataError = dataError;
  $effect.pre(() => {
    const nextConfig = config;
    const nextData = data;
    const nextDataError = dataError;
    untrack(() => {
      if (nextDataError || nextConfig !== previousConfig) {
        let configChanged = false;
        if (nextConfig !== previousConfig) {
          const nextDemoConfig = nextConfig ? buildMochartDemoConfig(nextConfig) : null;
          if (nextDemoConfig && mochartDemoConfig) {
            configChanged = hasConfigStructureChange(mochartDemoConfig.mochartConfig, nextDemoConfig.mochartConfig);
          }
          mochartDemoConfig = nextDemoConfig;
        }
        if (nextDataError || configChanged) {
          resetFocusAndFiltered();
        }
      }
      else if (nextData !== previousData) {
        const { configValidation, mochartConfig } = mochartDemoConfig ?? {};
        const valid = configValidation?.valid ?? false;
        if (!previousDataError && previousData && nextData && valid && mochartConfig) {
          if (focusedGroupIndex >= 0) {
            const property = mochartConfig.groupAxisConfig.property ?? '';
            const groupValue = previousData[focusedGroupIndex][property];
            let newFocusedGroupIndex = -1;
            let i, count = nextData.length;
            for (i = 0; i < count; i++) {
              if (nextData[i][property] === groupValue) {
                newFocusedGroupIndex = i;
                break;
              }
            }
            focusedGroupIndex = newFocusedGroupIndex;
          }
        }
        else {
          resetFocusAndFiltered();
        }
      }
      previousConfig = nextConfig;
      previousData = nextData;
      previousDataError = nextDataError;
    });
  });

  function onFocus(focusData: FocusData = {}) {
    const { seriesAxisId, seriesId, groupIndex } = focusData;
    if (seriesAxisId !== void 0) {
      focusedSeriesAxisId = seriesAxisId;
    }
    if (seriesId !== void 0) {
      focusedSeriesId = seriesId;
    }
    if (groupIndex !== void 0) {
      focusedGroupIndex = groupIndex;
    }
  }

  // The chart owns filter toggling now and reports the whole map.
  function onSeriesFilter({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }) {
    filteredSeriesIds = { ...nextFilteredSeriesIds };
  }

  function onChartCountToggle() {
    chartCount = chartCount === 1 ? 2 : 1;
  }

  const allowedChartCount = $derived(Math.floor(width / 2) > minChartWidthForSecondChart ? 2 : 1);
  const adjustedChartCount = $derived(Math.min(chartCount, allowedChartCount));
  const chartWidth = $derived(Math.floor((width - scrollWidthOffset) / adjustedChartCount));
</script>

<div class={"mochart-demo-tab-container row chart" + (active ? " active" : "")} bind:clientWidth={width}>
  <div class="editable-charts-sizer">
    <div class="editable-charts">
      {#if mochartDemoConfig && width > 0}
        {#each { length: adjustedChartCount } as _, i (i)}
          <EditableChart chartCount={chartCount} showChartCountControls={allowedChartCount > 1 && i === 0}
            width={chartWidth} {mochartDemoConfig} data={data ?? []} {dataError}
            isActive={active} {filteredSeriesIds} {focusedGroupIndex}
            {focusedSeriesAxisId} {focusedSeriesId} {onChartCountToggle}
            {onFocus} {onSeriesFilter} />
        {/each}
      {/if}
    </div>
  </div>
</div>
