// packages/mochart-svelte/src/DefaultChart.svelte
<script lang="ts">
  // Svelte wrapper around mochart's `createDefaultChart`: takes a raw `config`
  // (enhanced internally) and a plain array-of-objects `data`. Omit
  // `width`/`height` to have the chart track the container div's size.
  import { createDefaultChart } from '@mochart/core';
  import ChartHost from './ChartHost.svelte';
  import type { DefaultChartProps } from './types';

  let props: DefaultChartProps = $props();
</script>

<ChartHost create={createDefaultChart} {...props} />

// packages/mochart-angular/src/default-chart.ts
import { Component, Input } from '@angular/core';
import { createDefaultChart } from '@mochart/core';
import { BaseChart } from './base-chart';
import type { CreateChartFn } from './host';

/**
 * Angular wrapper around mochart's `createDefaultChart`: takes a raw `config`
 * (enhanced internally) and a plain array-of-objects `data`. Omit
 * `width`/`height` to have the chart track the host element's size;
 * `class`/`style` set on `<mochart-default-chart>` style that same element.
 */
@Component({
  selector: 'mochart-default-chart',
  template: '',
  styles: [':host { display: block; }']
})
export class DefaultChart extends BaseChart {
  @Input({ required: true }) config: any;
  @Input({ required: true }) data!: any[];

  protected override readonly create: CreateChartFn = createDefaultChart;

  protected override collectChartProps(): Record<string, any> {
    return {
      config: this.config,
      data: this.data
    };
  }
}
