// packages/mochart-demo-lit/src/components/rotation/demo-rotation.ts
import { html } from 'lit';
import { customElement, state } from 'lit/decorators.js';

import { defaultChart } from 'mochart-lit';

import { LightElement } from '../misc/LightElement';

import { configs, data, minWidth } from './rotationConfigs';

@customElement('demo-rotation')
export class DemoRotation extends LightElement {
  // Columns are sized from the card's measured width (not the window) so the
  // grid stays inside the padded shell.
  @state() private chartsWidth = 0;

  private resizeObserver: ResizeObserver | null = null;

  override firstUpdated(): void {
    const el = this.querySelector('.rotation-charts');
    if (el) {
      const measure = (): void => { this.chartsWidth = el.clientWidth; };
      this.resizeObserver = new ResizeObserver(measure);
      this.resizeObserver.observe(el);
      measure();
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    if (this.resizeObserver !== null) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }
  }

  override render(): unknown {
    const cols = Math.max(1, Math.floor(this.chartsWidth / minWidth));
    const colWidth = Math.floor(this.chartsWidth / cols);
    return html`<div class="rotation-container">
      <div class="rotation-charts">
        ${colWidth > 0 ? configs.map((config, i) => html`<div
            class=${'rotation-chart rotation-chart-' + i}
            style=${`left: ${(i % cols) * colWidth}px; top: ${Math.floor(i / cols) * colWidth}px; width: ${colWidth}px; height: ${colWidth}px;`}>
          ${defaultChart({ config, data, width: colWidth, height: colWidth })}
        </div>`) : null}
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-rotation': DemoRotation;
  }
}

// packages/mochart-demo-vue/src/components/rotation/DemoRotation.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';

import { DefaultChart } from 'mochart-vue';

import { configs, data, minWidth } from './rotationConfigs';

// Columns are sized from the card's measured width (not the window) so the
// grid stays inside the padded shell.
const chartsElement = ref<HTMLDivElement | null>(null);
const chartsWidth = ref(0);

let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  const el = chartsElement.value;
  if (el) {
    const measure = () => { chartsWidth.value = el.clientWidth; };
    resizeObserver = new ResizeObserver(measure);
    resizeObserver.observe(el);
    measure();
  }
});

onBeforeUnmount(() => {
  if (resizeObserver !== null) {
    resizeObserver.disconnect();
    resizeObserver = null;
  }
});

const cols = computed(() => Math.max(1, Math.floor(chartsWidth.value / minWidth)));
const colWidth = computed(() => Math.floor(chartsWidth.value / cols.value));
</script>

<template>
  <div class="rotation-container">
    <div ref="chartsElement" class="rotation-charts">
      <template v-if="colWidth > 0">
        <div v-for="(config, i) in configs" :key="i"
             :class="'rotation-chart rotation-chart-' + i"
             :style="`left: ${(i % cols) * colWidth}px; top: ${Math.floor(i / cols) * colWidth}px; width: ${colWidth}px; height: ${colWidth}px;`">
          <DefaultChart :config="config" :data="data" :width="colWidth" :height="colWidth" />
        </div>
      </template>
    </div>
  </div>
</template>
