// packages/mochart-demo-lit/src/components/gallery/gallery-page.ts
import { html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';

import { getGallerySections } from '@mochart/demo-common';
import type { GalleryItem, GallerySection } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';
import { icon } from '../misc/templates';
import { siteRootButton } from '../misc/mode-switcher';

import type { DemoData } from '../../types';

const pageIcons: Record<'transition' | 'rotation', string> = {
  transition: 'right-left',
  rotation: 'repeat'
};

@customElement('gallery-page')
export class GalleryPage extends LightElement {
  @property({ attribute: false }) demoData!: DemoData;
  @property({ attribute: false }) siteRootUrl: string | undefined = void 0;
  @property({ attribute: false }) onOpenDemo!: (demoId: string) => void;
  @property({ attribute: false }) onOpenPage!: (mode: 'transition' | 'rotation') => void;

  private onItemClick(item: GalleryItem): void {
    if (item.kind === 'demo') {
      this.onOpenDemo(item.id);
    }
    else {
      this.onOpenPage(item.mode);
    }
  }

  private renderItem(item: GalleryItem): unknown {
    return html`<button type="button" class="list-group-item list-group-item-action"
        @click=${() => this.onItemClick(item)}>${item.kind === 'page' ? icon({ name: pageIcons[item.mode], fixedWidth: true }) : nothing}<span class="mochart-demo-item-title">${item.title}</span>${item.description !== void 0
          ? html`<span class="mochart-demo-item-description">${item.description}</span>`
          : nothing}</button>`;
  }

  private renderSection(section: GallerySection): unknown {
    const list = html`<div class="list-group">${section.items.map(item => this.renderItem(item))}</div>`;
    const header = html`<span class="mochart-demo-gallery-section-title">${section.title}</span>${section.hint !== void 0
      ? html`<span class="mochart-demo-gallery-section-hint">${section.hint}</span>`
      : nothing}`;
    if (!section.collapsed) {
      return html`<section class="mochart-demo-gallery-section">
        <div class="mochart-demo-gallery-section-header">${header}</div>
        ${list}
      </section>`;
    }
    // Collapsed sections use native details/summary: no state to manage and
    // keyboard/screen-reader behavior comes for free.
    return html`<details class="mochart-demo-gallery-section">
      <summary class="mochart-demo-gallery-section-header">${icon({ name: 'flask', fixedWidth: true })}${header}</summary>
      ${list}
    </details>`;
  }

  override render(): unknown {
    return html`<div class="mochart-demo-container">
      ${this.siteRootUrl !== void 0
        ? html`<div class="mochart-demo-gallery-header">${siteRootButton(this.siteRootUrl)}</div>`
        : nothing}
      <div class="mochart-demo-content-pane">
        <div class="mochart-demo-gallery">
          ${getGallerySections(this.demoData).map(section => this.renderSection(section))}
        </div>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gallery-page': GalleryPage;
  }
}

// packages/mochart-demo-react/src/components/gallery/GalleryPage.tsx
import React from 'react';
import Icon from '../misc/Icon';

import { getGallerySections } from '@mochart/demo-common';
import type { GalleryItem, GallerySection } from '@mochart/demo-common';

import { SiteRootButton } from '../misc/ModeSwitcher';

import type { DemoData } from '../../types';

interface GalleryPageProps {
  demoData: DemoData;
  siteRootUrl?: string;
  onOpenDemo: (demoId: string) => void;
  onOpenPage: (mode: 'transition' | 'rotation') => void;
}

const pageIcons: Record<'transition' | 'rotation', string> = {
  transition: 'right-left',
  rotation: 'repeat'
};

function GalleryListItem({ item, onOpenDemo, onOpenPage }: { item: GalleryItem } & Pick<GalleryPageProps, 'onOpenDemo' | 'onOpenPage'>) {
  return (
    <button type="button" className="list-group-item list-group-item-action"
      onClick={() => {
        if (item.kind === 'demo') {
          onOpenDemo(item.id);
        }
        else {
          onOpenPage(item.mode);
        }
      }}>
      {item.kind === 'page' ? <Icon fixedWidth name={pageIcons[item.mode]} /> : null}
      <span className="mochart-demo-item-title">{item.title}</span>
      {item.description !== void 0 ? <span className="mochart-demo-item-description">{item.description}</span> : null}
    </button>
  );
}

function GallerySectionView({ section, onOpenDemo, onOpenPage }: { section: GallerySection } & Pick<GalleryPageProps, 'onOpenDemo' | 'onOpenPage'>) {
  const header = (
    <>
      <span className="mochart-demo-gallery-section-title">{section.title}</span>
      {section.hint !== void 0 ? <span className="mochart-demo-gallery-section-hint">{section.hint}</span> : null}
    </>
  );
  const list = (
    <div className="list-group">
      {section.items.map(item => (
        <GalleryListItem key={item.kind === 'demo' ? 'demo-' + item.id : 'page-' + item.mode}
          item={item} onOpenDemo={onOpenDemo} onOpenPage={onOpenPage} />
      ))}
    </div>
  );
  if (!section.collapsed) {
    return (
      <section className="mochart-demo-gallery-section">
        <div className="mochart-demo-gallery-section-header">{header}</div>
        {list}
      </section>
    );
  }
  // Collapsed sections use native details/summary: no state to manage and
  // keyboard/screen-reader behavior comes for free.
  return (
    <details className="mochart-demo-gallery-section">
      <summary className="mochart-demo-gallery-section-header">
        <Icon fixedWidth name="flask" />
        {header}
      </summary>
      {list}
    </details>
  );
}

export default function GalleryPage({ demoData, siteRootUrl, onOpenDemo, onOpenPage }: GalleryPageProps) {
  return (
    <div className="mochart-demo-container">
      {siteRootUrl !== void 0
        ? <div className="mochart-demo-gallery-header"><SiteRootButton siteRootUrl={siteRootUrl} /></div>
        : null}
      <div className="mochart-demo-content-pane">
        <div className="mochart-demo-gallery">
          {getGallerySections(demoData).map(section => (
            <GallerySectionView key={section.key} section={section} onOpenDemo={onOpenDemo} onOpenPage={onOpenPage} />
          ))}
        </div>
      </div>
    </div>
  );
}
