// packages/mochart-demo-react/src/components/sparkline/DemoSparkline.tsx
import { Fragment, useState } from 'react';

import { DefaultChart } from '@mochart/react';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';
import type { SparklineMetric } from '@mochart/demo-common';

import Icon from '../misc/Icon';
import ButtonWithTooltip from '../misc/ButtonWithTooltip';
import TopBar from '../misc/TopBar';

import type { OnBackToDemos } from '../../types';

interface DemoSparklineProps {
  siteRootUrl?: string;
  onBackToDemos: OnBackToDemos;
}

// Every sparkline mounts at the metric's explicit pixel size (no auto-sizing):
// inline metrics are word-sized, table cells larger.
function SparklineChart({ metric, step }: { metric: SparklineMetric; step: number }) {
  return <DefaultChart config={metric.config} data={metric.generate(step)} width={metric.width} height={metric.height} />;
}

function SparklineRow({ metric, step }: { metric: SparklineMetric; step: number }) {
  const data = metric.generate(step);
  return (
    <tr>
      <td>{metric.label}</td>
      <td className="sparkline-value">{metric.latestText(data)}</td>
      <td className="sparkline-cell">
        <DefaultChart config={metric.config} data={data} width={metric.width} height={metric.height} />
      </td>
    </tr>
  );
}

export default function DemoSparkline({ siteRootUrl, onBackToDemos }: DemoSparklineProps) {
  const text = demoText.sparklinePage;
  const [step, setStep] = useState(0);

  const onRandomize = () => setStep(prevStep => prevStep + 1);

  return (
    <div className="mochart-demo-container">
      <TopBar siteRootUrl={siteRootUrl} onBackToDemos={onBackToDemos} />
      <div className="sparkline-page">
        {/* The intro paragraph: copy segments with the inline metrics between them. */}
        <p className="sparkline-intro">
          {text.intro.map((segment, i) => {
            const metric = inlineSparklineMetrics[i];
            return (
              <Fragment key={i}>
                {segment}
                {metric !== undefined ? (
                  <span className="sparkline-inline"><SparklineChart metric={metric} step={step} /></span>
                ) : null}
              </Fragment>
            );
          })}
        </p>
        <div className="sparkline-controls">
          <ButtonWithTooltip id="sparkline-randomize" label={text.randomize.label} color="primary"
            tooltipText={text.randomize.tooltip} onClick={onRandomize} aria-label={text.randomize.aria}>
            <Icon fixedWidth={true} name="dice" />
          </ButtonWithTooltip>
        </div>
        <table className="sparkline-table">
          <thead>
            <tr>
              <th>{text.table.metric}</th>
              <th>{text.table.latest}</th>
              <th>{text.table.trend}</th>
            </tr>
          </thead>
          <tbody>
            {tableSparklineMetrics.map(metric => <SparklineRow key={metric.id} metric={metric} step={step} />)}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// packages/mochart-demo-angular/src/components/sparkline/demo-sparkline.ts
import { Component, Input, computed, signal } from '@angular/core';

import { DefaultChart } from '@mochart/angular';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';
import type { DataRow, SparklineMetric } from '@mochart/demo-common';

import { ButtonWithTooltip } from '../misc/button-with-tooltip';
import { Icon } from '../misc/icon';
import { TopBar } from '../misc/top-bar';

interface TableRow {
  metric: SparklineMetric;
  data: DataRow[];
  latest: string;
}

/**
 * The sparkline showcase page: the intro paragraph with word-sized charts
 * woven between the demoText.sparklinePage.intro segments, then the
 * small-multiples metrics table. Every chart mounts at the metric's explicit
 * width/height (no element sizing); Randomize bumps the step signal and the
 * computed datasets (and each row's latest text) follow.
 */
@Component({
  selector: 'app-demo-sparkline',
  imports: [DefaultChart, ButtonWithTooltip, Icon, TopBar],
  styles: [':host { display: contents; }'],
  template: `
    <div class="mochart-demo-container">
      <app-top-bar [siteRootUrl]="siteRootUrl" [onBackToDemos]="onBackToDemos" />
      <div class="sparkline-page">
        <p class="sparkline-intro">@for (segment of text.intro; track $index) {{{ segment }}@if (inlineMetrics[$index]; as metric) {<span class="sparkline-inline"><mochart-default-chart [config]="metric.config" [data]="inlineData()[$index]" [width]="metric.width" [height]="metric.height" /></span>}}</p>
        <div class="sparkline-controls">
          <app-button-with-tooltip id="sparkline-randomize" color="primary" [label]="text.randomize.label"
                                   [tooltipText]="text.randomize.tooltip" tooltipPlacement="top-start"
                                   [onClick]="onRandomize" [aria-label]="text.randomize.aria">
            <app-icon [fixedWidth]="true" name="dice" />
          </app-button-with-tooltip>
        </div>
        <table class="sparkline-table">
          <thead>
            <tr>
              <th>{{ text.table.metric }}</th>
              <th>{{ text.table.latest }}</th>
              <th>{{ text.table.trend }}</th>
            </tr>
          </thead>
          <tbody>
            @for (row of tableRows(); track row.metric.id) {
              <tr>
                <td>{{ row.metric.label }}</td>
                <td class="sparkline-value">{{ row.latest }}</td>
                <td class="sparkline-cell">
                  <mochart-default-chart [config]="row.metric.config" [data]="row.data"
                                         [width]="row.metric.width" [height]="row.metric.height" />
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class DemoSparkline {
  @Input() siteRootUrl?: string;
  @Input({ required: true }) onBackToDemos!: () => void;

  readonly text = demoText.sparklinePage;
  readonly inlineMetrics = inlineSparklineMetrics;

  readonly step = signal(0);

  readonly inlineData = computed<DataRow[][]>(() => {
    const step = this.step();
    return this.inlineMetrics.map(metric => metric.generate(step));
  });

  readonly tableRows = computed<TableRow[]>(() => {
    const step = this.step();
    return tableSparklineMetrics.map(metric => {
      const data = metric.generate(step);
      return { metric, data, latest: metric.latestText(data) };
    });
  });

  onRandomize = (): void => {
    this.step.update(step => step + 1);
  };
}
