// packages/mochart-demo-lit/src/components/single/demo-single.ts
import { html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { PropertyValues } from 'lit';

import { consumeShareState, demoText } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';

import '../demos/demos-tab';
import './chart-tab';
import './config-tab';
import './data-tab';
import '../misc/error-tab';

import type { DemoData, DemoMode, DemoConfig, DataRow, OnDemoModeChanged, OnDemoChanged } from '../../types';

type DataError = string | boolean | null;

const eventKeyChart = 1;
const eventKeyConfig = 2;
const eventKeyData = 3;
const eventKeyDemo = 4;

function getActiveKeyForInitialDemoId(initialDemoId: string): number {
  return initialDemoId === 'demos' ? eventKeyDemo : eventKeyChart;
}

@customElement('demo-single')
export class DemoSingle extends LightElement {
  @property({ attribute: false }) demoData!: DemoData;
  @property({ attribute: false }) demoMode!: DemoMode;
  @property({ attribute: false }) initialDemoId!: string;
  @property({ attribute: false }) onDemoModeChanged!: OnDemoModeChanged;
  @property({ attribute: false }) onDemoChanged!: OnDemoChanged;

  @state() private activeKey = eventKeyChart;
  @state() private demoId = '';
  // Config/data edits made on the Config/Data tabs stay "pending" until the
  // Chart tab is shown again (so the chart animates one combined change).
  // pendingConfig/pendingData are reactive so the Chart tab badge updates.
  @state() private pendingConfig: DemoConfig | null = null;
  @state() private pendingData: DataRow[] | null = null;
  private pendingDataError: DataError = false;
  @state() private config: DemoConfig | null = null;
  @state() private data: DataRow[] | null = null;
  @state() private dataError: DataError = false;
  @state() private viewingConfig: DemoConfig | null = null;
  @state() private viewingData: DataRow[] | null = null;
  @state() private viewingDataError: DataError = false;

  override willUpdate(changed: PropertyValues<this>): void {
    if (!changed.has('initialDemoId')) {
      return;
    }
    const initialDemoId = this.initialDemoId;
    if (!this.hasUpdated) {
      // A share link carries edited config/data in the URL hash; it overrides
      // the demo's own config/data for the initial mount only.
      const sharedState = initialDemoId !== 'demos' ? consumeShareState() : null;
      this.activeKey = getActiveKeyForInitialDemoId(initialDemoId);
      this.demoId = initialDemoId;
      this.config = initialDemoId !== 'demos' ? (sharedState?.config ?? this.demoData.demoObjectMap[initialDemoId].config) : null;
      this.data = initialDemoId !== 'demos' ? (sharedState?.data ?? this.demoData.demoObjectMap[initialDemoId].data) : null;
      this.dataError = false;
      this.viewingConfig = this.config;
      this.viewingData = this.data;
      this.viewingDataError = false;
      return;
    }
    // When the routed demo changes, reload its config/data (and promote them
    // straight to the visible chart, matching the react demo's lifecycle).
    this.activeKey = getActiveKeyForInitialDemoId(initialDemoId);
    this.demoId = initialDemoId;
    if (initialDemoId === 'demos') {
      this.config = null;
      this.data = null;
      this.dataError = null;
      this.viewingConfig = null;
      this.viewingData = null;
    }
    else {
      this.config = this.demoData.demoObjectMap[initialDemoId].config;
      this.data = this.demoData.demoObjectMap[initialDemoId].data;
      this.dataError = null;
      this.pendingConfig = this.config;
      this.pendingData = this.data;
      this.chartShown();
    }
  }

  private chartShown(): void {
    if (this.pendingConfig !== null || this.pendingData !== null || this.pendingDataError !== null) {
      if (this.pendingConfig !== null) {
        this.viewingConfig = this.pendingConfig;
        this.pendingConfig = null;
      }
      if (this.pendingData !== null) {
        this.viewingData = this.pendingData;
        this.pendingData = null;
      }
      if (this.pendingDataError !== null) {
        this.viewingDataError = this.pendingDataError;
        this.pendingDataError = null;
      }
    }
  }

  private handleSelect(nextActiveKey: number): void {
    const previousActiveKey = this.activeKey;
    this.activeKey = nextActiveKey;
    if (nextActiveKey === eventKeyChart && previousActiveKey !== eventKeyChart) {
      this.chartShown();
    }
  }

  private onConfigChange = (nextPendingConfig: DemoConfig): void => {
    this.pendingConfig = nextPendingConfig;
  };

  private onConfigReset = (): void => {
    const resetConfig = { ...this.demoData.demoObjectMap[this.demoId].config };
    this.pendingConfig = resetConfig;
    this.config = resetConfig;
  };

  private onDataChange = (nextPendingData: DataRow[]): void => {
    this.pendingData = nextPendingData;
    this.pendingDataError = false;
  };

  private onDataError = (errorMessage: string): void => {
    this.pendingDataError = errorMessage;
  };

  private onDataReset = (): void => {
    // give it a new array reference so children know to update
    this.pendingData = this.demoData.demoObjectMap[this.demoId].data.slice();
    this.pendingDataError = false;
  };

  private onDemoChange = (nextDemoId: string): void => {
    this.onDemoChanged(nextDemoId);
  };

  // Applied config/data edits are held until the Chart tab is shown; badge the
  // Chart tab so it's visible that something is waiting there.
  private get hasPendingChanges(): boolean {
    return this.activeKey !== eventKeyChart && (this.pendingConfig !== null || this.pendingData !== null);
  }

  private renderTab(eventKey: number, label: string): unknown {
    const badge = eventKey === eventKeyChart && this.hasPendingChanges;
    return html`<li class="nav-item">
      <button type="button" class=${'nav-link' + (this.activeKey === eventKey ? ' active' : '')}
              title=${badge ? demoText.tabs.chartPendingTitle : nothing}
              @click=${() => this.handleSelect(eventKey)}>
        ${label}${badge ? html`<span class="mochart-pending-badge" aria-hidden="true"></span>` : nothing}
      </button>
    </li>`;
  }

  override render(): unknown {
    const demosTab = html`<demos-tab .active=${this.activeKey === eventKeyDemo} .demoData=${this.demoData} .demoMode=${this.demoMode} .demoId=${this.demoId}
        .onDemoModeChanged=${this.onDemoModeChanged} .onDemoChange=${this.onDemoChange}></demos-tab>`;
    return html`<div class="mochart-demo-container">
      <div class="mochart-demo-tabs-container">
        <ul class="nav nav-tabs">
          ${this.renderTab(eventKeyDemo, demoText.tabs.demos)}
          ${this.renderTab(eventKeyChart, demoText.tabs.chart)}
          ${this.renderTab(eventKeyConfig, demoText.tabs.config)}
          ${this.renderTab(eventKeyData, demoText.tabs.data)}
        </ul>
      </div>
      ${this.initialDemoId === 'demos'
        ? html`<div class="mochart-demo-content-pane">
            <div class="mochart-demo-content single-tab">${demosTab}</div>
          </div>`
        : html`<div class="mochart-demo-content-pane">
            <div class="mochart-demo-content">
              <error-tab .active=${this.activeKey === eventKeyDemo} .content=${() => demosTab}></error-tab>
              <error-tab .active=${this.activeKey === eventKeyChart} .content=${() =>
                html`<chart-tab .active=${this.activeKey === eventKeyChart} .config=${this.viewingConfig} .data=${this.viewingData} .dataError=${this.viewingDataError}></chart-tab>`}></error-tab>
              <error-tab .active=${this.activeKey === eventKeyConfig} .content=${() =>
                html`<config-tab .active=${this.activeKey === eventKeyConfig} .config=${this.config!} .onConfigChange=${this.onConfigChange} .onConfigReset=${this.onConfigReset}></config-tab>`}></error-tab>
              <error-tab .active=${this.activeKey === eventKeyData} .content=${() =>
                html`<data-tab .active=${this.activeKey === eventKeyData} .config=${this.viewingConfig!} .data=${this.data!}
                    .onDataChange=${this.onDataChange} .onDataError=${this.onDataError} .onDataReset=${this.onDataReset}></data-tab>`}></error-tab>
            </div>
          </div>`}
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-single': DemoSingle;
  }
}

// packages/mochart-demo-vue/src/components/single/DemoSingle.vue
<script setup lang="ts">
import { computed, ref, shallowRef, watch } from 'vue';

import { consumeShareState, demoText } from '@mochart/demo-common';

import DemosTab from '../demos/DemosTab.vue';
import ChartTab from './ChartTab.vue';
import ConfigTab from './ConfigTab.vue';
import DataTab from './DataTab.vue';
import ErrorTab from '../misc/ErrorTab.vue';

import type { DemoData, DemoMode, DemoConfig, DataRow, OnDemoModeChanged, OnDemoChanged } from '../../types';

interface Props {
  demoData: DemoData;
  demoMode: DemoMode;
  initialDemoId: string;
  onDemoModeChanged: OnDemoModeChanged;
  onDemoChanged: OnDemoChanged;
}

type DataError = string | boolean | null;

const eventKeyChart = 1;
const eventKeyConfig = 2;
const eventKeyData = 3;
const eventKeyDemo = 4;

function getActiveKeyForInitialDemoId(initialDemoId: string): number {
  return initialDemoId === 'demos' ? eventKeyDemo : eventKeyChart;
}

const props = defineProps<Props>();

const activeKey = ref(getActiveKeyForInitialDemoId(props.initialDemoId));

// A share link carries edited config/data in the URL hash; it overrides the
// demo's own config/data for the initial mount only.
const sharedState = props.initialDemoId !== 'demos' ? consumeShareState() : null;

// Config/data edits made on the Config/Data tabs stay "pending" until the
// Chart tab is shown again (so the chart animates one combined change).
const demoId = ref(props.initialDemoId);
const pendingConfig = shallowRef<DemoConfig | null>(null);
const pendingData = shallowRef<DataRow[] | null>(null);
const pendingDataError = shallowRef<DataError>(false);
const config = shallowRef<DemoConfig | null>(props.initialDemoId !== 'demos' ? (sharedState?.config ?? props.demoData.demoObjectMap[props.initialDemoId].config) : null);
const data = shallowRef<DataRow[] | null>(props.initialDemoId !== 'demos' ? (sharedState?.data ?? props.demoData.demoObjectMap[props.initialDemoId].data) : null);
const dataError = shallowRef<DataError>(false);
const viewingConfig = shallowRef<DemoConfig | null>(props.initialDemoId !== 'demos' ? (sharedState?.config ?? props.demoData.demoObjectMap[props.initialDemoId].config) : null);
const viewingData = shallowRef<DataRow[] | null>(props.initialDemoId !== 'demos' ? (sharedState?.data ?? props.demoData.demoObjectMap[props.initialDemoId].data) : null);
const viewingDataError = shallowRef<DataError>(false);

function chartShown() {
  if (pendingConfig.value !== null || pendingData.value !== null || pendingDataError.value !== null) {
    if (pendingConfig.value !== null) {
      viewingConfig.value = pendingConfig.value;
      pendingConfig.value = null;
    }
    if (pendingData.value !== null) {
      viewingData.value = pendingData.value;
      pendingData.value = null;
    }
    if (pendingDataError.value !== null) {
      viewingDataError.value = pendingDataError.value;
      pendingDataError.value = null;
    }
  }
}

function handleSelect(nextActiveKey: number) {
  const previousActiveKey = activeKey.value;
  activeKey.value = nextActiveKey;
  if (nextActiveKey === eventKeyChart && previousActiveKey !== eventKeyChart) {
    chartShown();
  }
}

// When the routed demo changes, reload its config/data (and promote them
// straight to the visible chart, matching the react demo's lifecycle).
watch(() => props.initialDemoId, (initialDemoId) => {
  activeKey.value = getActiveKeyForInitialDemoId(initialDemoId);
  demoId.value = initialDemoId;
  if (initialDemoId === 'demos') {
    config.value = null;
    data.value = null;
    dataError.value = null;
    viewingConfig.value = null;
    viewingData.value = null;
  }
  else {
    config.value = props.demoData.demoObjectMap[initialDemoId].config;
    data.value = props.demoData.demoObjectMap[initialDemoId].data;
    dataError.value = null;
    pendingConfig.value = config.value;
    pendingData.value = data.value;
    chartShown();
  }
});

function onConfigChange(nextPendingConfig: DemoConfig) {
  pendingConfig.value = nextPendingConfig;
}

function onConfigReset() {
  const resetConfig = { ...props.demoData.demoObjectMap[demoId.value].config };
  pendingConfig.value = resetConfig;
  config.value = resetConfig;
}

function onDataChange(nextPendingData: DataRow[]) {
  pendingData.value = nextPendingData;
  pendingDataError.value = false;
}

function onDataError(errorMessage: string) {
  pendingDataError.value = errorMessage;
}

function onDataReset() {
  // give it a new array reference so children know to update
  pendingData.value = props.demoData.demoObjectMap[demoId.value].data.slice();
  pendingDataError.value = false;
}

function onDemoChange(nextDemoId: string) {
  props.onDemoChanged(nextDemoId);
}

// Applied config/data edits are held until the Chart tab is shown; badge the
// Chart tab so it's visible that something is waiting there.
const hasPendingChanges = computed(() =>
  activeKey.value !== eventKeyChart && (pendingConfig.value !== null || pendingData.value !== null));
</script>

<template>
  <div class="mochart-demo-container">
    <div class="mochart-demo-tabs-container">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyDemo ? ' active' : '')"
                  @click="handleSelect(eventKeyDemo)">
            {{ demoText.tabs.demos }}
          </button>
        </li>
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyChart ? ' active' : '')"
                  :title="hasPendingChanges ? demoText.tabs.chartPendingTitle : void 0"
                  @click="handleSelect(eventKeyChart)">
            {{ demoText.tabs.chart }}<span v-if="hasPendingChanges" class="mochart-pending-badge" aria-hidden="true"></span>
          </button>
        </li>
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyConfig ? ' active' : '')"
                  @click="handleSelect(eventKeyConfig)">
            {{ demoText.tabs.config }}
          </button>
        </li>
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyData ? ' active' : '')"
                  @click="handleSelect(eventKeyData)">
            {{ demoText.tabs.data }}
          </button>
        </li>
      </ul>
    </div>
    <div v-if="props.initialDemoId === 'demos'" class="mochart-demo-content-pane">
      <div class="mochart-demo-content single-tab">
        <DemosTab :active="activeKey === eventKeyDemo" :demo-data="props.demoData" :demo-mode="props.demoMode" :demo-id="demoId"
                  :on-demo-mode-changed="props.onDemoModeChanged" :on-demo-change="onDemoChange" />
      </div>
    </div>
    <div v-else class="mochart-demo-content-pane">
      <div class="mochart-demo-content">
        <ErrorTab :active="activeKey === eventKeyDemo">
          <DemosTab :active="activeKey === eventKeyDemo" :demo-data="props.demoData" :demo-mode="props.demoMode" :demo-id="demoId"
                    :on-demo-mode-changed="props.onDemoModeChanged" :on-demo-change="onDemoChange" />
        </ErrorTab>
        <ErrorTab :active="activeKey === eventKeyChart">
          <ChartTab :active="activeKey === eventKeyChart" :config="viewingConfig" :data="viewingData" :data-error="viewingDataError" />
        </ErrorTab>
        <ErrorTab :active="activeKey === eventKeyConfig">
          <ConfigTab :active="activeKey === eventKeyConfig" :config="config!" :on-config-change="onConfigChange" :on-config-reset="onConfigReset" />
        </ErrorTab>
        <ErrorTab :active="activeKey === eventKeyData">
          <DataTab :active="activeKey === eventKeyData" :config="viewingConfig!" :data="data!"
                   :on-data-change="onDataChange" :on-data-error="onDataError" :on-data-reset="onDataReset" />
        </ErrorTab>
      </div>
    </div>
  </div>
</template>
