// packages/mochart-demo-svelte/src/components/single/DemoSingle.svelte
<script lang="ts">
  import { consumeShareState, demoText } from '@mochart/demo-common';

  import DemosTab from '../demos/DemosTab.svelte';
  import ChartTab from './ChartTab.svelte';
  import ConfigTab from './ConfigTab.svelte';
  import DataTab from './DataTab.svelte';
  import ErrorTab from '../misc/ErrorTab.svelte';

  import type { DemoData, DemoMode, DemoConfig, DataRow, OnDemoModeChanged, OnDemoChanged } from '../../types';

  interface Props {
    demoData: DemoData;
    demoMode: DemoMode;
    initialDemoId: string;
    onDemoModeChanged: OnDemoModeChanged;
    onDemoChanged: OnDemoChanged;
  }

  type DataError = string | boolean | null;

  const eventKeyChart = 1;
  const eventKeyConfig = 2;
  const eventKeyData = 3;
  const eventKeyDemo = 4;

  function getActiveKeyForInitialDemoId(initialDemoId: string): number {
    return initialDemoId === 'demos' ? eventKeyDemo : eventKeyChart;
  }

  let { demoData, demoMode, initialDemoId, onDemoModeChanged, onDemoChanged }: Props = $props();

  // Props intentionally seed local state with their initial value only; the
  // $effect.pre below re-syncs everything when the routed demo changes.
  // svelte-ignore state_referenced_locally
  let activeKey = $state(getActiveKeyForInitialDemoId(initialDemoId));

  // A share link carries edited config/data in the URL hash; it overrides
  // the demo's own config/data for the initial mount only.
  // svelte-ignore state_referenced_locally
  const sharedState = initialDemoId !== 'demos' ? consumeShareState() : null;

  // Config/data edits made on the Config/Data tabs stay "pending" until the
  // Chart tab is shown again (so the chart animates one combined change).
  // svelte-ignore state_referenced_locally
  let demoId = $state(initialDemoId);
  let pendingConfig = $state.raw<DemoConfig | null>(null);
  let pendingData = $state.raw<DataRow[] | null>(null);
  let pendingDataError = $state.raw<DataError>(false);
  // svelte-ignore state_referenced_locally
  let config = $state.raw<DemoConfig | null>(initialDemoId !== 'demos' ? (sharedState?.config ?? demoData.demoObjectMap[initialDemoId].config) : null);
  // svelte-ignore state_referenced_locally
  let data = $state.raw<DataRow[] | null>(initialDemoId !== 'demos' ? (sharedState?.data ?? demoData.demoObjectMap[initialDemoId].data) : null);
  let dataError = $state.raw<DataError>(false);
  // svelte-ignore state_referenced_locally
  let viewingConfig = $state.raw<DemoConfig | null>(initialDemoId !== 'demos' ? (sharedState?.config ?? demoData.demoObjectMap[initialDemoId].config) : null);
  // svelte-ignore state_referenced_locally
  let viewingData = $state.raw<DataRow[] | null>(initialDemoId !== 'demos' ? (sharedState?.data ?? demoData.demoObjectMap[initialDemoId].data) : null);
  let viewingDataError = $state.raw<DataError>(false);

  function chartShown() {
    if (pendingConfig !== null || pendingData !== null || pendingDataError !== null) {
      if (pendingConfig !== null) {
        viewingConfig = pendingConfig;
        pendingConfig = null;
      }
      if (pendingData !== null) {
        viewingData = pendingData;
        pendingData = null;
      }
      if (pendingDataError !== null) {
        viewingDataError = pendingDataError;
        pendingDataError = null;
      }
    }
  }

  function handleSelect(nextActiveKey: number) {
    const previousActiveKey = activeKey;
    activeKey = nextActiveKey;
    if (nextActiveKey === eventKeyChart && previousActiveKey !== eventKeyChart) {
      chartShown();
    }
  }

  // When the routed demo changes, reload its config/data (and promote them
  // straight to the visible chart, matching the react demo's lifecycle).
  // svelte-ignore state_referenced_locally
  let previousInitialDemoId = initialDemoId;
  $effect.pre(() => {
    if (initialDemoId !== previousInitialDemoId) {
      previousInitialDemoId = initialDemoId;
      activeKey = getActiveKeyForInitialDemoId(initialDemoId);
      demoId = initialDemoId;
      if (initialDemoId === 'demos') {
        config = null;
        data = null;
        dataError = null;
        viewingConfig = null;
        viewingData = null;
      }
      else {
        config = demoData.demoObjectMap[initialDemoId].config;
        data = demoData.demoObjectMap[initialDemoId].data;
        dataError = null;
        pendingConfig = config;
        pendingData = data;
        chartShown();
      }
    }
  });

  function onConfigChange(nextPendingConfig: DemoConfig) {
    pendingConfig = nextPendingConfig;
  }

  function onConfigReset() {
    const resetConfig = { ...demoData.demoObjectMap[demoId].config };
    pendingConfig = resetConfig;
    config = resetConfig;
  }

  function onDataChange(nextPendingData: DataRow[]) {
    pendingData = nextPendingData;
    pendingDataError = false;
  }

  function onDataError(errorMessage: string) {
    pendingDataError = errorMessage;
  }

  function onDataReset() {
    // give it a new array reference so children know to update
    pendingData = demoData.demoObjectMap[demoId].data.slice();
    pendingDataError = false;
  }

  function onDemoChange(nextDemoId: string) {
    onDemoChanged(nextDemoId);
  }

  // Applied config/data edits are held until the Chart tab is shown; badge the
  // Chart tab so it's visible that something is waiting there.
  const hasPendingChanges = $derived(activeKey !== eventKeyChart && (pendingConfig !== null || pendingData !== null));
</script>

<div class="mochart-demo-container">
  <div class="mochart-demo-tabs-container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <button type="button" class={"nav-link" + (activeKey === eventKeyDemo ? " active" : "")}
                onclick={() => handleSelect(eventKeyDemo)}>
          {demoText.tabs.demos}
        </button>
      </li>
      <li class="nav-item">
        <button type="button" class={"nav-link" + (activeKey === eventKeyChart ? " active" : "")}
                title={hasPendingChanges ? demoText.tabs.chartPendingTitle : void 0}
                onclick={() => handleSelect(eventKeyChart)}>
          {demoText.tabs.chart}{#if hasPendingChanges}<span class="mochart-pending-badge" aria-hidden="true"></span>{/if}
        </button>
      </li>
      <li class="nav-item">
        <button type="button" class={"nav-link" + (activeKey === eventKeyConfig ? " active" : "")}
                onclick={() => handleSelect(eventKeyConfig)}>
          {demoText.tabs.config}
        </button>
      </li>
      <li class="nav-item">
        <button type="button" class={"nav-link" + (activeKey === eventKeyData ? " active" : "")}
                onclick={() => handleSelect(eventKeyData)}>
          {demoText.tabs.data}
        </button>
      </li>
    </ul>
  </div>
  {#if initialDemoId === 'demos'}
    <div class="mochart-demo-content-pane">
      <div class="mochart-demo-content single-tab">
        <DemosTab active={activeKey === eventKeyDemo} {demoData} {demoMode} {demoId}
                  {onDemoModeChanged} {onDemoChange} />
      </div>
    </div>
  {:else}
    <div class="mochart-demo-content-pane">
      <div class="mochart-demo-content">
        <ErrorTab active={activeKey === eventKeyDemo}>
          <DemosTab active={activeKey === eventKeyDemo} {demoData} {demoMode} {demoId}
                    {onDemoModeChanged} {onDemoChange} />
        </ErrorTab>
        <ErrorTab active={activeKey === eventKeyChart}>
          <ChartTab active={activeKey === eventKeyChart} config={viewingConfig} data={viewingData} dataError={viewingDataError} />
        </ErrorTab>
        <ErrorTab active={activeKey === eventKeyConfig}>
          <ConfigTab active={activeKey === eventKeyConfig} config={config!} {onConfigChange} {onConfigReset} />
        </ErrorTab>
        <ErrorTab active={activeKey === eventKeyData}>
          <DataTab active={activeKey === eventKeyData} config={viewingConfig!} data={data!}
                   {onDataChange} {onDataError} {onDataReset} />
        </ErrorTab>
      </div>
    </div>
  {/if}
</div>

// packages/mochart-demo-vue/src/components/single/DemoSingle.vue
<script setup lang="ts">
import { computed, ref, shallowRef, watch } from 'vue';

import { consumeShareState, demoText } from '@mochart/demo-common';

import DemosTab from '../demos/DemosTab.vue';
import ChartTab from './ChartTab.vue';
import ConfigTab from './ConfigTab.vue';
import DataTab from './DataTab.vue';
import ErrorTab from '../misc/ErrorTab.vue';

import type { DemoData, DemoMode, DemoConfig, DataRow, OnDemoModeChanged, OnDemoChanged } from '../../types';

interface Props {
  demoData: DemoData;
  demoMode: DemoMode;
  initialDemoId: string;
  onDemoModeChanged: OnDemoModeChanged;
  onDemoChanged: OnDemoChanged;
}

type DataError = string | boolean | null;

const eventKeyChart = 1;
const eventKeyConfig = 2;
const eventKeyData = 3;
const eventKeyDemo = 4;

function getActiveKeyForInitialDemoId(initialDemoId: string): number {
  return initialDemoId === 'demos' ? eventKeyDemo : eventKeyChart;
}

const props = defineProps<Props>();

const activeKey = ref(getActiveKeyForInitialDemoId(props.initialDemoId));

// A share link carries edited config/data in the URL hash; it overrides the
// demo's own config/data for the initial mount only.
const sharedState = props.initialDemoId !== 'demos' ? consumeShareState() : null;

// Config/data edits made on the Config/Data tabs stay "pending" until the
// Chart tab is shown again (so the chart animates one combined change).
const demoId = ref(props.initialDemoId);
const pendingConfig = shallowRef<DemoConfig | null>(null);
const pendingData = shallowRef<DataRow[] | null>(null);
const pendingDataError = shallowRef<DataError>(false);
const config = shallowRef<DemoConfig | null>(props.initialDemoId !== 'demos' ? (sharedState?.config ?? props.demoData.demoObjectMap[props.initialDemoId].config) : null);
const data = shallowRef<DataRow[] | null>(props.initialDemoId !== 'demos' ? (sharedState?.data ?? props.demoData.demoObjectMap[props.initialDemoId].data) : null);
const dataError = shallowRef<DataError>(false);
const viewingConfig = shallowRef<DemoConfig | null>(props.initialDemoId !== 'demos' ? (sharedState?.config ?? props.demoData.demoObjectMap[props.initialDemoId].config) : null);
const viewingData = shallowRef<DataRow[] | null>(props.initialDemoId !== 'demos' ? (sharedState?.data ?? props.demoData.demoObjectMap[props.initialDemoId].data) : null);
const viewingDataError = shallowRef<DataError>(false);

function chartShown() {
  if (pendingConfig.value !== null || pendingData.value !== null || pendingDataError.value !== null) {
    if (pendingConfig.value !== null) {
      viewingConfig.value = pendingConfig.value;
      pendingConfig.value = null;
    }
    if (pendingData.value !== null) {
      viewingData.value = pendingData.value;
      pendingData.value = null;
    }
    if (pendingDataError.value !== null) {
      viewingDataError.value = pendingDataError.value;
      pendingDataError.value = null;
    }
  }
}

function handleSelect(nextActiveKey: number) {
  const previousActiveKey = activeKey.value;
  activeKey.value = nextActiveKey;
  if (nextActiveKey === eventKeyChart && previousActiveKey !== eventKeyChart) {
    chartShown();
  }
}

// When the routed demo changes, reload its config/data (and promote them
// straight to the visible chart, matching the react demo's lifecycle).
watch(() => props.initialDemoId, (initialDemoId) => {
  activeKey.value = getActiveKeyForInitialDemoId(initialDemoId);
  demoId.value = initialDemoId;
  if (initialDemoId === 'demos') {
    config.value = null;
    data.value = null;
    dataError.value = null;
    viewingConfig.value = null;
    viewingData.value = null;
  }
  else {
    config.value = props.demoData.demoObjectMap[initialDemoId].config;
    data.value = props.demoData.demoObjectMap[initialDemoId].data;
    dataError.value = null;
    pendingConfig.value = config.value;
    pendingData.value = data.value;
    chartShown();
  }
});

function onConfigChange(nextPendingConfig: DemoConfig) {
  pendingConfig.value = nextPendingConfig;
}

function onConfigReset() {
  const resetConfig = { ...props.demoData.demoObjectMap[demoId.value].config };
  pendingConfig.value = resetConfig;
  config.value = resetConfig;
}

function onDataChange(nextPendingData: DataRow[]) {
  pendingData.value = nextPendingData;
  pendingDataError.value = false;
}

function onDataError(errorMessage: string) {
  pendingDataError.value = errorMessage;
}

function onDataReset() {
  // give it a new array reference so children know to update
  pendingData.value = props.demoData.demoObjectMap[demoId.value].data.slice();
  pendingDataError.value = false;
}

function onDemoChange(nextDemoId: string) {
  props.onDemoChanged(nextDemoId);
}

// Applied config/data edits are held until the Chart tab is shown; badge the
// Chart tab so it's visible that something is waiting there.
const hasPendingChanges = computed(() =>
  activeKey.value !== eventKeyChart && (pendingConfig.value !== null || pendingData.value !== null));
</script>

<template>
  <div class="mochart-demo-container">
    <div class="mochart-demo-tabs-container">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyDemo ? ' active' : '')"
                  @click="handleSelect(eventKeyDemo)">
            {{ demoText.tabs.demos }}
          </button>
        </li>
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyChart ? ' active' : '')"
                  :title="hasPendingChanges ? demoText.tabs.chartPendingTitle : void 0"
                  @click="handleSelect(eventKeyChart)">
            {{ demoText.tabs.chart }}<span v-if="hasPendingChanges" class="mochart-pending-badge" aria-hidden="true"></span>
          </button>
        </li>
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyConfig ? ' active' : '')"
                  @click="handleSelect(eventKeyConfig)">
            {{ demoText.tabs.config }}
          </button>
        </li>
        <li class="nav-item">
          <button type="button" :class="'nav-link' + (activeKey === eventKeyData ? ' active' : '')"
                  @click="handleSelect(eventKeyData)">
            {{ demoText.tabs.data }}
          </button>
        </li>
      </ul>
    </div>
    <div v-if="props.initialDemoId === 'demos'" class="mochart-demo-content-pane">
      <div class="mochart-demo-content single-tab">
        <DemosTab :active="activeKey === eventKeyDemo" :demo-data="props.demoData" :demo-mode="props.demoMode" :demo-id="demoId"
                  :on-demo-mode-changed="props.onDemoModeChanged" :on-demo-change="onDemoChange" />
      </div>
    </div>
    <div v-else class="mochart-demo-content-pane">
      <div class="mochart-demo-content">
        <ErrorTab :active="activeKey === eventKeyDemo">
          <DemosTab :active="activeKey === eventKeyDemo" :demo-data="props.demoData" :demo-mode="props.demoMode" :demo-id="demoId"
                    :on-demo-mode-changed="props.onDemoModeChanged" :on-demo-change="onDemoChange" />
        </ErrorTab>
        <ErrorTab :active="activeKey === eventKeyChart">
          <ChartTab :active="activeKey === eventKeyChart" :config="viewingConfig" :data="viewingData" :data-error="viewingDataError" />
        </ErrorTab>
        <ErrorTab :active="activeKey === eventKeyConfig">
          <ConfigTab :active="activeKey === eventKeyConfig" :config="config!" :on-config-change="onConfigChange" :on-config-reset="onConfigReset" />
        </ErrorTab>
        <ErrorTab :active="activeKey === eventKeyData">
          <DataTab :active="activeKey === eventKeyData" :config="viewingConfig!" :data="data!"
                   :on-data-change="onDataChange" :on-data-error="onDataError" :on-data-reset="onDataReset" />
        </ErrorTab>
      </div>
    </div>
  </div>
</template>
