// packages/mochart-demo-react/src/components/random/RandomDataTab.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import TextAreaContent from '../misc/TextAreaContent';

function formatData(dataJSON) {
  return JSON.stringify(dataJSON).replace(/,/g, ', ').replace(/},/g, '},\n');
}

class RandomMochartDataTab extends Component {
  static propTypes = {
    active: PropTypes.bool,
    data: PropTypes.array.isRequired
  };

  constructor(props) {
    super(props);
    this.state = { dataText: null };
  }

  UNSAFE_componentWillMount() {
    const { data } = this.props;
    this.setState({dataText: formatData(data)});
  }

  UNSAFE_componentWillReceiveProps(nextProps) {
    const { data } = nextProps;
    if (data !== this.props.data) {
      this.setState({dataText: formatData(data)});
    }
  }

  render() {
    const { active } = this.props;
    const { dataText } = this.state;

    return (
      <div className={"mochart-demo-tab-container col data" + (active ? " active": "")}>
        <div className="mochart-demo-tab-content">
          <TextAreaContent value={dataText} onChange={() => {}}/>
        </div>
      </div>
    );
  }
}

export default RandomMochartDataTab;

// packages/mochart-demo-svelte/src/components/random/RandomDataTab.svelte
<script>
  import { untrack } from 'svelte';

  import TextAreaContent from '../misc/TextAreaContent.svelte';

  function formatData(dataJSON) {
    return JSON.stringify(dataJSON).replace(/,/g, ', ').replace(/},/g, '},\n');
  }

  let { active = false, data } = $props();

  let dataText = $state(formatData(data));

  let previousData = data;
  $effect.pre(() => {
    const nextData = data;
    untrack(() => {
      if (nextData !== previousData) {
        previousData = nextData;
        dataText = formatData(nextData);
      }
    });
  });
</script>

<div class={"mochart-demo-tab-container col data" + (active ? " active" : "")}>
  <div class="mochart-demo-tab-content">
    <TextAreaContent value={dataText} onChange={() => {}} />
  </div>
</div>
