// packages/mochart-demo-svelte/src/components/single/ChartTab.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  import { hasConfigStructureChange } from 'mochart';

  import buildMochartDemoConfig from '../../config/mochartDemoConfig';

  import EditableChart from './EditableChart.svelte';

  import type { DemoConfig, DataRow, MochartDemoConfig, FocusData, FilteredSeriesIds } from '../../types';

  interface Props {
    config?: DemoConfig | null;
    data?: DataRow[] | null;
    dataError?: string | boolean | null;
    active?: boolean;
  }

  const minChartWidthForSecondChart = 480;
  const scrollWidthOffset = 20;
  const defaultChartCount = 1;

  let { config = null, data = null, dataError = false, active = false }: Props = $props();

  // Measured width of the tab (the react demo wrapped this tab in the
  // react-sizer HOC for the same purpose).
  let width = $state(0);

  let chartCount = $state(defaultChartCount);
  let focusedSeriesAxisId = $state.raw<string | null>(null);
  let focusedSeriesId = $state.raw<string | null>(null);
  let focusedGroupIndex = $state(-1);
  let filteredSeriesIds = $state.raw<FilteredSeriesIds>({});
  let mochartDemoConfig = $state.raw<MochartDemoConfig | null>(config ? buildMochartDemoConfig(config) : null);

  function resetFocusAndFiltered() {
    focusedSeriesAxisId = null;
    focusedSeriesId = null;
    focusedGroupIndex = -1;
    filteredSeriesIds = {};
  }

  // Mirror the react lifecycle: a config change rebuilds the demo config and
  // resets focus/filter state when the structure changed (or on data errors);
  // a data change remaps the focused group index onto the new data.
  let previousConfig = config;
  let previousData = data;
  let previousDataError = dataError;
  $effect.pre(() => {
    const nextConfig = config;
    const nextData = data;
    const nextDataError = dataError;
    untrack(() => {
      if (nextDataError || nextConfig !== previousConfig) {
        let configChanged = false;
        if (nextConfig !== previousConfig) {
          const nextDemoConfig = nextConfig ? buildMochartDemoConfig(nextConfig) : null;
          if (nextDemoConfig && mochartDemoConfig) {
            configChanged = hasConfigStructureChange(mochartDemoConfig.mochartConfig, nextDemoConfig.mochartConfig);
          }
          mochartDemoConfig = nextDemoConfig;
        }
        if (nextDataError || configChanged) {
          resetFocusAndFiltered();
        }
      }
      else if (nextData !== previousData) {
        const { configValidation, mochartConfig } = mochartDemoConfig ?? {};
        const valid = configValidation?.valid ?? false;
        if (!previousDataError && previousData && nextData && valid && mochartConfig) {
          if (focusedGroupIndex >= 0) {
            const property = mochartConfig.groupAxisConfig.property ?? '';
            const groupValue = previousData[focusedGroupIndex][property];
            let newFocusedGroupIndex = -1;
            let i, count = nextData.length;
            for (i = 0; i < count; i++) {
              if (nextData[i][property] === groupValue) {
                newFocusedGroupIndex = i;
                break;
              }
            }
            focusedGroupIndex = newFocusedGroupIndex;
          }
        }
        else {
          resetFocusAndFiltered();
        }
      }
      previousConfig = nextConfig;
      previousData = nextData;
      previousDataError = nextDataError;
    });
  });

  function onFocus(focusData: FocusData = {}) {
    const { seriesAxisId, seriesId, groupIndex } = focusData;
    if (seriesAxisId !== void 0) {
      focusedSeriesAxisId = seriesAxisId;
    }
    if (seriesId !== void 0) {
      focusedSeriesId = seriesId;
    }
    if (groupIndex !== void 0) {
      focusedGroupIndex = groupIndex;
    }
  }

  // The chart owns filter toggling now and reports the whole map.
  function onSeriesFilter({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }) {
    filteredSeriesIds = { ...nextFilteredSeriesIds };
  }

  function onChartCountToggle() {
    chartCount = chartCount === 1 ? 2 : 1;
  }

  const allowedChartCount = $derived(Math.floor(width / 2) > minChartWidthForSecondChart ? 2 : 1);
  const adjustedChartCount = $derived(Math.min(chartCount, allowedChartCount));
  const chartWidth = $derived(Math.floor((width - scrollWidthOffset) / adjustedChartCount));
</script>

<div class={"mochart-demo-tab-container row chart" + (active ? " active" : "")} bind:clientWidth={width}>
  <div class="editable-charts-sizer">
    <div class="editable-charts">
      {#if mochartDemoConfig && width > 0}
        {#each { length: adjustedChartCount } as _, i (i)}
          <EditableChart chartCount={chartCount} showChartCountControls={allowedChartCount > 1 && i === 0}
            width={chartWidth} {mochartDemoConfig} data={data ?? []} {dataError}
            isActive={active} {filteredSeriesIds} {focusedGroupIndex}
            {focusedSeriesAxisId} {focusedSeriesId} {onChartCountToggle}
            {onFocus} {onSeriesFilter} />
        {/each}
      {/if}
    </div>
  </div>
</div>

// packages/mochart-demo-lit/src/components/single/chart-tab.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { ref } from 'lit/directives/ref.js';
import type { PropertyValues } from 'lit';

import { hasConfigStructureChange } from '@mochart/core';

import { buildMochartDemoConfig } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';
import { ElementSizeController } from '../misc/ElementSizeController';
import './editable-chart';

import type { DemoConfig, DataRow, MochartDemoConfig, FocusData, FilteredSeriesIds } from '../../types';

const minChartWidthForSecondChart = 480;
const scrollWidthOffset = 20;
const defaultChartCount = 1;

@customElement('chart-tab')
export class ChartTab extends LightElement {
  @property({ attribute: false }) config: DemoConfig | null = null;
  @property({ attribute: false }) data: DataRow[] | null = null;
  @property({ attribute: false }) dataError: string | boolean | null = false;
  @property({ attribute: false }) active = false;

  // Measured width of the tab (the react demo wrapped this tab in the
  // react-sizer HOC for the same purpose).
  private size = new ElementSizeController(this);

  @state() private chartCount = defaultChartCount;
  @state() private focusedSeriesAxisId: string | null = null;
  @state() private focusedSeriesId: string | null = null;
  @state() private focusedGroupIndex = -1;
  @state() private filteredSeriesIds: FilteredSeriesIds = {};
  @state() private mochartDemoConfig: MochartDemoConfig | null = null;

  private resetFocusAndFiltered(): void {
    this.focusedSeriesAxisId = null;
    this.focusedSeriesId = null;
    this.focusedGroupIndex = -1;
    this.filteredSeriesIds = {};
  }

  // Mirror the react lifecycle: a config change rebuilds the demo config and
  // resets focus/filter state when the structure changed (or on data errors);
  // a data change remaps the focused group index onto the new data.
  override willUpdate(changed: PropertyValues<this>): void {
    if (!this.hasUpdated) {
      this.mochartDemoConfig = this.config ? buildMochartDemoConfig(this.config) : null;
      return;
    }
    if (!changed.has('config') && !changed.has('data') && !changed.has('dataError')) {
      return;
    }
    const previousConfig = changed.has('config') ? (changed.get('config') as DemoConfig | null) : this.config;
    const previousData = changed.has('data') ? (changed.get('data') as DataRow[] | null) : this.data;
    const previousDataError = changed.has('dataError') ? (changed.get('dataError') as string | boolean | null) : this.dataError;
    if (this.dataError || this.config !== previousConfig) {
      let configChanged = false;
      if (this.config !== previousConfig) {
        const nextDemoConfig = this.config ? buildMochartDemoConfig(this.config) : null;
        if (nextDemoConfig && this.mochartDemoConfig) {
          configChanged = hasConfigStructureChange(this.mochartDemoConfig.mochartConfig, nextDemoConfig.mochartConfig);
        }
        this.mochartDemoConfig = nextDemoConfig;
      }
      if (this.dataError || configChanged) {
        this.resetFocusAndFiltered();
      }
    }
    else if (this.data !== previousData) {
      const { configValidation, mochartConfig } = this.mochartDemoConfig ?? {};
      const valid = configValidation?.valid ?? false;
      if (!previousDataError && previousData && this.data && valid && mochartConfig) {
        if (this.focusedGroupIndex >= 0) {
          const property = mochartConfig.groupAxisConfig.property ?? '';
          const groupValue = previousData[this.focusedGroupIndex][property];
          let newFocusedGroupIndex = -1;
          let i, count = this.data.length;
          for (i = 0; i < count; i++) {
            if (this.data[i][property] === groupValue) {
              newFocusedGroupIndex = i;
              break;
            }
          }
          this.focusedGroupIndex = newFocusedGroupIndex;
        }
      }
      else {
        this.resetFocusAndFiltered();
      }
    }
  }

  private onFocus = (focusData: FocusData = {}): void => {
    const { seriesAxisId, seriesId, groupIndex } = focusData;
    if (seriesAxisId !== void 0) {
      this.focusedSeriesAxisId = seriesAxisId;
    }
    if (seriesId !== void 0) {
      this.focusedSeriesId = seriesId;
    }
    if (groupIndex !== void 0) {
      this.focusedGroupIndex = groupIndex;
    }
  };

  // The chart owns filter toggling now and reports the whole map.
  private onSeriesFilter = ({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }): void => {
    this.filteredSeriesIds = { ...nextFilteredSeriesIds };
  };

  private onChartCountToggle = (): void => {
    this.chartCount = this.chartCount === 1 ? 2 : 1;
  };

  override render(): unknown {
    const width = this.size.width;
    const allowedChartCount = Math.floor(width / 2) > minChartWidthForSecondChart ? 2 : 1;
    const adjustedChartCount = Math.min(this.chartCount, allowedChartCount);
    const chartWidth = Math.floor((width - scrollWidthOffset) / adjustedChartCount);
    const chartIndices = Array.from({ length: adjustedChartCount }, (unused, index) => index + 1);
    return html`<div ${ref(this.size.attach)} class=${'mochart-demo-tab-container row chart' + (this.active ? ' active' : '')}>
      <div class="editable-charts-sizer">
        <div class="editable-charts">
          ${this.mochartDemoConfig && width > 0
            ? chartIndices.map(i => html`<editable-chart
                .chartCount=${this.chartCount} .showChartCountControls=${allowedChartCount > 1 && i === 1} .showShareButton=${i === 1}
                .width=${chartWidth} .mochartDemoConfig=${this.mochartDemoConfig!} .data=${this.data ?? []} .dataError=${this.dataError}
                .isActive=${this.active} .filteredSeriesIds=${this.filteredSeriesIds} .focusedGroupIndex=${this.focusedGroupIndex}
                .focusedSeriesAxisId=${this.focusedSeriesAxisId} .focusedSeriesId=${this.focusedSeriesId} .onChartCountToggle=${this.onChartCountToggle}
                .onFocus=${this.onFocus} .onSeriesFilter=${this.onSeriesFilter}></editable-chart>`)
            : null}
        </div>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'chart-tab': ChartTab;
  }
}
