// packages/mochart-demo-svelte/src/components/misc/BackToDemosButton.svelte
<script lang="ts">
  // Back link from a demo view to the gallery landing page.
  import { demoText } from '@mochart/demo-common';

  import Icon from './Icon.svelte';

  interface Props {
    onBackToDemos: () => void;
  }

  let { onBackToDemos }: Props = $props();
</script>

<button type="button" class="demo-btn demo-btn-secondary mochart-demo-back-button"
        title={demoText.backToDemos.tooltip} aria-label={demoText.backToDemos.aria}
        onclick={onBackToDemos}>
  <Icon name="chevron-left" /> {demoText.backToDemos.label}
</button>

// packages/mochart-demo-vue/src/components/misc/BackToDemosButton.vue
<script setup lang="ts">
import { demoText } from '@mochart/demo-common';

import Icon from './Icon.vue';

// Back link from a demo view to the gallery landing page.
interface Props {
  onBackToDemos: () => void;
}

const props = defineProps<Props>();
</script>

<template>
  <button type="button" class="btn btn-secondary mochart-demo-back-button"
          :title="demoText.backToDemos.tooltip" :aria-label="demoText.backToDemos.aria"
          @click="props.onBackToDemos()">
    <Icon name="chevron-left" /> {{ demoText.backToDemos.label }}
  </button>
</template>
