// packages/mochart-demo-svelte/src/components/misc/SiteRootButton.svelte
<script lang="ts">
  // Link back to the docs site root (a real anchor so middle-click works).
  // Renders nothing when no site root is configured (standalone dev/build).
  import { demoText } from '@mochart/demo-common';

  import Icon from './Icon.svelte';

  interface Props {
    siteRootUrl?: string;
  }

  let { siteRootUrl = void 0 }: Props = $props();
</script>

{#if siteRootUrl !== void 0}
  <a class="btn btn-secondary mochart-demo-site-root-button" href={siteRootUrl}
     title={demoText.siteRootLink.tooltip} aria-label={demoText.siteRootLink.aria}>
    <Icon name="house" /> {demoText.siteRootLink.shortLabel}
  </a>
{/if}

// packages/mochart-demo-vue/src/components/misc/SiteRootButton.vue
<script setup lang="ts">
import { demoText } from '@mochart/demo-common';

import Icon from './Icon.vue';

// Link back to the docs site root (a real anchor so middle-click works).
// Renders nothing when no site root is configured (standalone dev/build).
interface Props {
  siteRootUrl?: string;
}

const props = withDefaults(defineProps<Props>(), {
  siteRootUrl: undefined
});
</script>

<template>
  <a v-if="props.siteRootUrl !== undefined" class="demo-btn demo-btn-secondary mochart-demo-site-root-button"
     :href="props.siteRootUrl" :title="demoText.siteRootLink.tooltip" :aria-label="demoText.siteRootLink.aria">
    <Icon name="house" /> {{ demoText.siteRootLink.shortLabel }}
  </a>
</template>
