// packages/mochart-demo-angular/src/components/misc/text-area-content.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-text-area-content',
  styles: [
    ':host { display: contents; }',
    /* The react demo measured the pane with react-sizer to set explicit pixel
       sizes on the textarea; plain css sizing does the same job here. */
    '.text-area-content { display: flex; flex: 1 1 auto; width: 100%; min-width: 0; min-height: 0; }',
    'textarea { width: 100%; height: 100%; resize: none; }'
  ],
  template: `
    <div class="text-area-content">
      <textarea [value]="value" (input)="onInput($event)"></textarea>
    </div>
  `
})
export class TextAreaContent {
  @Input({ required: true }) value!: string;
  @Input({ required: true }) onChange!: (value: string) => void;

  onInput(event: Event): void {
    this.onChange((event.currentTarget as HTMLTextAreaElement).value);
  }
}

// packages/mochart-demo-vue/src/components/misc/TextAreaContent.vue
<script setup lang="ts">
interface Props {
  value: string;
  onChange: (value: string) => void;
}

const props = defineProps<Props>();

function onInput(event: Event) {
  props.onChange((event.currentTarget as HTMLTextAreaElement).value);
}
</script>

<template>
  <div class="text-area-content">
    <textarea :value="props.value" @input="onInput"></textarea>
  </div>
</template>

<style scoped>
/* The react demo measured the pane with react-sizer to set explicit pixel
   sizes on the textarea; plain css sizing does the same job here. */
.text-area-content {
  display: flex;
  flex: 1 1 auto;
  width: 100%;
  min-width: 0;
  min-height: 0;
}
textarea {
  width: 100%;
  height: 100%;
  resize: none;
}
</style>
